adobe/aem-core-forms-components

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/aemform/AEMFormImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/aemform/AEMForm.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/aemform/package-info.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/aemform/AEMFormImplTest.java
bundles/core/src/test/resources/aemform/exporter-aemform-1.json
bundles/core/src/test/resources/aemform/test-content.json
examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/forms/aemform/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/aemform.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/clientlibs/editor/js/aemform.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/clientlibs/runtime/formapp/js/formapp.js

CQ-4305130 Enabling support to skip focus on field of Form

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/README.md

Updating AEM Forms Container component read me

---

.circleci/config.yml

Moving CI to JDK 11

---

bundles/core/pom.xml
bundles/core/src/test/java/com/adobe/cq/forms/core/context/FormsCoreComponentTestContext.java
parent/pom.xml

- Moving to junit 5
- Upgraded few compile time dependencies

Upgrading compile time dependencies

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/_cq_dialog/.content.xml

Move away from Layout type as per instructions from -
https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/reference-materials/granite-ui/api/jcr_root/libs/granite/ui/components/legacy/coral2/migration.html#layout-concept
and do not add extra empty option in select element
Results:
Width of edit dialog remains same and text in RTE doesn't trigger
width changes
No duplication of blank element options in theme dropdown
@review @rismehta
@DoD done

CQ-4318408 AEM Forms Container component fixes

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/aemform.html

This is to avoid issues with double dots in case locale is not
available in iframe
@review @rismehta

CQ-4318532 Use default locale if not available

---

.circleci/ci/build.js
.circleci/ci/ci.js
.circleci/ci/it-tests.js
.circleci/config.yml
.gitignore
parent/pom.xml
pom.xml
ui.tests/README.md
ui.tests/pom.xml
ui.tests/test-module/.eslintrc.js
ui.tests/test-module/README.md
ui.tests/test-module/cypress.json
ui.tests/test-module/libs/commons/commons.js
ui.tests/test-module/libs/commons/formsConstants.js
ui.tests/test-module/libs/commons/guideSelectors.js
ui.tests/test-module/libs/commons/sitesConstants.js
ui.tests/test-module/libs/commons/sitesSelectors.js
ui.tests/test-module/libs/fixtures/example.json
ui.tests/test-module/libs/plugins/index.js
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/libs/support/functions.js
ui.tests/test-module/libs/support/index.js
ui.tests/test-module/package-lock.json
ui.tests/test-module/package.json
ui.tests/test-module/specs/aemformcontainer.spec.js

CQ-4305013 Enabling e2e test execution #donotmerge

---

parent/pom.xml
ui.tests/README.md
ui.tests/test-module/README.md
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/specs/aemformcontainer.spec.js

- Removed unused code
- Fixed vulnerabilities
@review @vdua
DOD(Yes)

CQ-4305013 Adding support for e2e test execution

---

ui.tests/test-module/specs/aemformcontainer.spec.js

- Removed unused code
- Fixed vulnerabilities
@review @vdua
DOD(Yes)

 CQ-4305013 Adding support for e2e test execution

---

examples/README.md
examples/all/pom.xml
examples/pom.xml
parent/pom.xml

- Added all modules for examples
@review @vdua
DOD(Yes)

CQ-4305012 Creating all package for examples

---

examples/README.md
parent/pom.xml

- Fixing security issue with a maven dependency
@review @vdua
DOD(Yes)

CQ-4305012 Fixing read me

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/iframe.html

CQ-4320321 Indicate robots to ignore iframe

---

examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml

CQ-4305012 Adding illustration for aem forms container component

---

bundles/core/pom.xml
parent/pom.xml

- Fixed the maven dependency to include java 8 classes
@review @vdua
DOD(Yes)

CQ-4305012 Test cases execution failure in java 8 environment

---

.circleci/config.yml

CQ-4321561 Java 8 build using circle CI

---

ui.tests/test-module/libs/support/commands.js

Fixing flakiness in cypress

---

README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v1/link/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v1/link/link.html
ui.tests/test-module/specs/formsportallinkcomponent.spec.js

Also fix one non BEM class name
@review @rismehta @vdua

CQ-4301939 Improve component README

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/clientlibs/runtime/formapp/js/formapp.js

@Review : @rismehta
@dod : none
Removed class from cq-guides and added code local to formapp

CQ-4322633 For sign enabled embedded AF, in-form signing not working

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/clientlibs/site/css/aemform.less
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/formcontainer.html

Update AEM Form Container BEM

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/aemform.html

CQ-4340563 AEM Form component iframe width attribute issue

---

ui.tests/test-module/package-lock.json
ui.tests/test-module/package.json

Fixed vulnerable dependencies and have to force resolutions to avoid vulnerability because the cypress-snapshot-plugin has not been updated in a long time.

Update dependency with non-vulnerable resolutions for cypress tests

---

bundles/core/pom.xml
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/services/formsportal/OperationManagerImpl.java
parent/pom.xml

CQ-4344197 Updating maven bundle plugin version

---

ui.tests/test-module/package-lock.json

@trivial Updating package-lock.json

---

README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/container.html

@trivial updating read me and removing path from container component

---

README.md
bundles/core/pom.xml
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
bundles/core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
bundles/core/src/test/resources/form/formcontainer/test-content.json
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-base/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/container/.content.xml
examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/adaptive-form/container/.content.xml
ui.apps/pom.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/clientlibs/editor/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/clientlibs/editor/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_design_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_editConfig.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_template/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editor/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editor/js.txt
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editor/js/editDialog.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/draftsandsubmissions/v1/draftsandsubmissions/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/searchlister/v1/searchlister/clientlibs/site/.content.xml
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/specs/formcontainer.spec.js

Container v2

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/textinput.html

CQ-4345762 Updating readme with java script data attribute bindings

---

examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/templates/af-blank-v2/policies/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/templates/af-blank-v2/structure/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-examples/blank/.content.xml
ui.tests/test-module/specs/textinput.spec.js

CQ-4344327 update text input test cases for form container v2

---

README.md
examples/all/pom.xml
examples/ui.apps/pom.xml
examples/ui.content/pom.xml
it/content/pom.xml
parent/pom.xml

Cloud profile build

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/_cq_dialog/.content.xml

Change the accordion to tabs in cq:dialog for container, textinput & datepicker
CQ-4346932
Manually

Cq 4346932

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/clientlibs/editorhook/js/EditListeners.js

CQ-4346953 Fix wizard redirect in Sites page for AEM in Unified Shell

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormConstants.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormStructureParserImpl.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormStructureParserImplTest.java
bundles/core/src/test/resources/form/formstructparser/test-content.json

CQ-4346472 Correct form path correlation in sling models.

---

ui.apps/pom.xml

CQ-4347143 Include runtime clientlib in cloud profile

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/CheckBoxGroupImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/CheckBoxImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DatePickerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DropDownImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FileInputImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/NumberInputImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/PanelImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextInputImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFieldImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractOptionsFieldImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/LabelImpl.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/AbstractContainerImplTest.java
bundles/core/src/test/resources/form/checkbox/test-content.json
bundles/core/src/test/resources/form/checkboxgroup/test-content.json
bundles/core/src/test/resources/form/datepicker/test-content.json
bundles/core/src/test/resources/form/dropdown/test-content.json
bundles/core/src/test/resources/form/fileinput/test-content.json
bundles/core/src/test/resources/form/formcontainer/test-content.json
bundles/core/src/test/resources/form/numberinput/test-content.json
bundles/core/src/test/resources/form/panel/test-content.json
bundles/core/src/test/resources/form/textinput/test-content.json
examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/adaptive-form/textinput/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/_cq_template.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/_cq_template.xml

Making field type mandatory and making abstract classes public for easy customization

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/clientlibs/editorhook/js/EditListeners.js

CQ-4347278 Fix wizard redirect in Sites page for AEM in Unified Shell

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/CheckBoxGroupImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/CheckBoxImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DatePickerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DropDownImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FileInputImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/NumberInputImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/PanelImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextInputImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/TextInput.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractComponentImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/views/Views.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/views/package-info.java
bundles/core/src/test/java/com/adobe/cq/forms/core/Utils.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DatePickerImplTest.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DropDownImplTest.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FileInputImplTest.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/NumberInputImplTest.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/PanelImplTest.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextInputImplTest.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

Support resource.adaptTo for Forms Core Components as its required for DoR as well as HTTP API (that do not have `SlingHTTPServletRequest`). Also, support JsonViews (jackson) for serialising authoring specific properties through Sling models.

CQ-4346127 Support Sling Model adaptation from resource

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/textinput/_cq_template.xml

@trivial Adding cq template to proxy

---

.gitignore
parent/pom.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/clientlibs/core-forms-components-runtime-all/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/clientlibs/core-forms-components-runtime-all/css.txt
ui.apps/src/main/content/jcr_root/apps/core/fd/clientlibs/core-forms-components-runtime-all/js.txt
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/page/v1/page/customfooterlibs.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/page/v1/page/customheaderlibs.html
ui.frontend/clientlib.config.js

CQ-4346519 Async loading of runtime clientlibs

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/editor/js/editDialog.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/textinput.html

CQ-4347177 update jcr property name in cqdialog

---

ui.frontend/__tests__/guidebridge.test.js
ui.frontend/__tests__/resources/form.json
ui.frontend/__tests__/utils.test.js
ui.frontend/pom.xml
ui.frontend/src/FormData.js
ui.frontend/src/GuideBridge.js
ui.frontend/src/Response.js
ui.frontend/src/constants.js
ui.frontend/src/view/FormContainer.js

CQ-4347467 GuideBridge APIs

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/core/src/test/resources/form/formcontainer/exporter-formcontainer.json
bundles/core/src/test/resources/form/formcontainer/test-content.json

@trivial Fixing form container v1 implementation

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/Base.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractContainerImpl.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

CQ-4347493 Support for localization in HTTP API

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/_cq_editConfig.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/js/tabs.js

Add edit dialog

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/Base.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractContainerImpl.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

* CQ-4347493 Support for localization in HTTP API @review @vdua
DOD(yes)
* CQ-4347493 Support for localization in HTTP API @review @vdua DOD(yes)

CQ-4347493 Support for localization in HTTP API (#146)

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml

hide v1 accordion in v2 dialog

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormStructureParserImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormStructureParser.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/package-info.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormStructureParserImplTest.java
bundles/core/src/test/resources/form/formstructparser/test-content.json
ui.apps/src/main/content/jcr_root/apps/core/fd/components/page/v1/page/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/page/v1/page/customfooterlibs.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/page/v1/page/customheaderlibs.html

Changes related to clientLibRef

---

it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/panelcontainer/.content.xml
it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/panelcontainer/basic/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/panelcontainer/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/panelcontainer/basic/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/commons/v1/fieldTemplates/label.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/_cq_editConfig.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/editor/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/editor/js/panelcontainer.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/panelcontainer.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/panelcontainer.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/responsiveGrid.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/simple.html
ui.frontend/src/constants.js
ui.frontend/src/utils.js
ui.frontend/src/view/FormFieldBase.js
ui.frontend/src/view/FormPanel.js
ui.tests/test-module/specs/panelcontainer.spec.js
ui.tests/test-module/specs/panelcontainer/panelcontainer.runtime.spec.js

CQ-4346477 Added repeatability support, runtime tests including repeatability, updated authouring tests.

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/footer/v1/footer/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/runtime/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/.content.xml
ui.frontend/pom.xml

 Update ui.frontend artifact id

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/footer/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/policies/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/templates/af-blank-v2/policies/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/templates/af-blank-v2/structure/.content.xml
ui.tests/test-module/specs/button/button.authoring.spec.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.authoring.spec.js
ui.tests/test-module/specs/datepicker/datepicker.authoring.spec.js
ui.tests/test-module/specs/footer.spec.js
ui.tests/test-module/specs/image/image.authoring.spec.js
ui.tests/test-module/specs/numberinput/numberinput.authoring.spec.js
ui.tests/test-module/specs/panelcontainer/panelcontainer.authoring.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.authoring.spec.js
ui.tests/test-module/specs/text/text.authoring.spec.js
ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

Update IT collateral for enabling header and footer components

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
parent/pom.xml

   @trivial Removing system path from maven dependency

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/dropdown/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/clientlibs/core-forms-components-runtime-all/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/footer/v1/footer/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/runtime/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/.content.xml
ui.tests/test-module/specs/dropdown/dropdown.authoring.spec.js

Fix issues in readme and clientlib categories

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/_cq_dialog/.content.xml

Fix dialog

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/_cq_dialog/.content.xml

Updating the dialog for checkboxgroup

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/accordion/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/accordion.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/textinput.html
ui.tests/test-module/specs/accordion/accordion.authoring.spec.js

@trivial Fix docs

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datepicker/basic/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/numberinput/basic/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/button.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/checkboxgroup.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/datepicker.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/dropdown.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/fileinput.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/numberinput.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/radiobutton.html
ui.frontend/src/view/FormFieldBase.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
ui.tests/test-module/specs/textinput/textinput.runtime.spec.js

Merge dev to master

---

.circleci/config.yml
parent/pom.xml

@trivial Using the latest aem image

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormMetaDataImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormMetaData.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
bundles/core/src/test/java/com/adobe/cq/forms/core/Utils.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
bundles/core/src/test/resources/form/formcontainer/exporter-formcontainer.json
bundles/core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
bundles/core/src/test/resources/schema/0.11.0-Pre/adaptive-form.schema.json

@trivial Fixing form container sling model

---

.circleci/ci/it-tests.js
.circleci/config.yml
it/config/pom.xml
it/config/src/main/content/META-INF/vault/filter.xml
it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
parent/pom.xml
pom.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
ui.frontend/__tests__/guidebridge.test.js
ui.frontend/src/FormData.js
ui.frontend/src/GuideBridge.js
ui.frontend/src/HTTPAPILayer.js
ui.frontend/src/constants.js
ui.frontend/src/index.js
ui.frontend/src/utils.js
ui.frontend/src/view/FormContainer.js

CQ-4347957 Prefill Support

---

it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/text/.content.xml
it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/text/basic/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/text/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/text/basic/.content.xml
ui.tests/test-module/specs/text/text.runtime.spec.js

Added runtime test cases for text component

Added runtime test cases for text component

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/accordion.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/site/css.txt
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/site/css/accordionview.css
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/site/js/accordionview.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/css.txt
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/css/tabsview.css
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/js/tabs.js
ui.frontend/src/view/FormPanel.js

fix accordion & tabs slightly & add BEM

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/js/fileinputview.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputview.js
ui.frontend/package-lock.json
ui.frontend/src/HTTPAPILayer.js
ui.frontend/src/utils.js

CQ-4348225 Fixing prefill with file attachment

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

Fix resource adaptation of FormContainer

---

ui.frontend/package-lock.json
ui.frontend/package.json

@trivial updating af core version

---

ui.apps/pom.xml

update wcm core component dependency range

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FileInputImpl.java
bundles/core/src/test/resources/form/fileinput/test-content.json

Cq 4348225

---

ui.apps/pom.xml

@trivial fixing brackets in apps dependency

---

it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/templates/af-blank-v2/initial/.content.xml

Add cq:template property in initial content

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/css/textinputview.css

CQ-4348380 add default height of textarea

---

ui.tests/test-module/specs/title/title.authoring.spec.js

Uncommenting forms editor test case for title authoring.

uncommenting authoring title test case

---

ui.frontend/src/HTTPAPILayer.js

@trivial add missing return in getForms

---

it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/image/.content.xml
it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/image/basic/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/image/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/image/basic/.content.xml
ui.tests/test-module/package-lock.json
ui.tests/test-module/specs/image/image.runtime.spec.js

Added support for runtime testcases of image component.

CQ-4348322 - Image component runtime testcases added

---

ui.apps/pom.xml

@trivial Removing core adaptive form group

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/_cq_dialog/.content.xml

CQ-4348857 Conditional show hide of background tab in panel broken.

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/draftsandsubmissions/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/accordion/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/button/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/checkboxgroup/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/container/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/datepicker/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/dropdown/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/fileinput/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/footer/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/image/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/numberinput/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/pageheader/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/panelcontainer/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/radiobutton/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/tabsontop/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/text/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/textinput/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/title/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/wizard/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/linkcomponent/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/searchlister/.content.xml
examples/ui.content/src/main/content/META-INF/vault/filter.xml
examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml
examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/policies/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/policies/.content.xml
ui.apps/pom.xml
ui.tests/test-module/specs/formcontainer.spec.js

@trivial Changing component groups

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractOptionsFieldImpl.java

@trivial Fixing localization

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/guideThankYouPage.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
ui.frontend/package-lock.json
ui.frontend/package.json

- added default thank you page @review @vdua
DOD(Yes)

CQ-4348830 Updating submit success and submit error handler

---

it/content/src/main/content/jcr_root/conf/core-components-it/_sling_configs/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/_sling_configs/_rep_policy.xml
it/content/src/main/content/jcr_root/conf/core-components-it/_sling_configs/com.adobe.cq.wcm.core.components.config.HtmlPageItemsConfig/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/policies/_rep_policy.xml
it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/templates/_rep_policy.xml

Fixes CQ-4348894, CQ-4348859
forms-user needs crx:replicate permmission on policies and template folder to replicate template structure and policies when forms-user publishes AF. forms-user inherits permissions from content-author group.
Added sling:config node for theme association with template and template-type. AF blank template or any new template created using template-type are associated with canvas theme by default.

Template changes - ACL and Theme association

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/_cq_editConfig.xml

CQ-4348977 Show Rule Editor in Horizontal Tabs

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/editor/js/editDialog.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/js/fileinputwidget.js

CQ-4348973 File attachment fixes

---

ui.frontend/__tests__/utils.test.js
ui.frontend/src/utils.js

Support wrapped prefill json for FDM Prefill Service

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
bundles/core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
bundles/core/src/test/resources/schema/0.11.0-Pre/adaptive-form.schema.json
ui.frontend/src/utils.js
ui.frontend/src/view/FormFieldBase.js

CQ-4349126 Changes to label and description not reflected in markup

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/_cq_dialog/.content.xml

removing disable property for a static image in the dialog
[CQ-4348971](https://jira.corp.adobe.com/browse/CQ-4348971)

[CQ-4348971] remove disable property from static image

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/clientlibs/editor/js/editDialog.js

CQ-4349095 Hiding bindref select button for fdm submit action dialog

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/css/wizard.css
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/wizard.html

CQ-4348690 fix wizard next/prv button issue

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/css/wizard.css
ui.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/wizard.html

Reverts adobe/aem-core-forms-components#297

Revert "CQ-4348690 fix wizard next/prv button issue"

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/css/dropdownview.css
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/css/wizard.css
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/wizard.html

 [CQ-4349416] fix wizard issue

---

.circleci/ci/it-tests.js
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFieldImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/package-info.java
ui.tests/pom.xml

Ignore runtime specific data attributes in authoring

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImplTest.java

Do not return fd:rules status if status is none

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/_cq_dialog/.content.xml

`Hide Title` checkbox to hide the panel's title has been added (taken from base component)
https://jira.corp.adobe.com/browse/CQ-4349201

CQ-4349201 - Hide Title Option Missing in Panel Dialogs

---

.circleci/ci/it-tests.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v1/title/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/draftsandsubmissions/v1/draftsandsubmissions/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v1/link/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v2/link/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/portallister/v1/portallister/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/searchlister/v1/searchlister/_cq_dialog/.content.xml

Changed the `trackingFeature` string in the cq_dialog's `.content.xml` to the appropriate adaptiveform version of the string
Components affected:
- Accordion
- Title
Added the attribute to the following `formsportal` components
- `draftsandsubmissions`
- `link`
- `portallister`
- `searchlister`
https://jira.corp.adobe.com/browse/CQ-4349354

CQ-4349354 - Enable Omega Tracking - For portal components

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/clientlibs/editor/js/editDialog.js

CQ-4349511 Fixed name field in dialog not checking for invalid characters

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputview.js
ui.frontend/src/utils.js

CQ-4348721 Fixed number input for safari browsers

---

bundles/af-core/pom.xml
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImplTest.java
bundles/af-core/src/test/resources/form/image/exporter-empty-image.json
bundles/af-core/src/test/resources/form/image/test-content.json
examples/ui.apps/pom.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/_cq_editConfig.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/image.html

This PR fixes multiple issues with the image component:
1. Drag drop of image component was giving lot of 404s in console. This was due to the fact that image sling model was incorrectly returning non-null `imageSrc` even if there's no image associated with the component.
2. Drag and dropping an image directly from assets browser was inserting a foundation component thus leading to incorrect structure
3. Empty image component's editable was styled incorrectly with placeholder's height coming as less than expected.
4. Incorrect APIs being used in sightly template of image (eg `image.imageLink.valid`)

CQ-4349561 Drag drop image component gives error in console

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/PanelImpl.java
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/editor/js/panelcontainer.js

Make the warpData edit dialog js work for panel, tabs and accordion.

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormComponent.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImplTest.java
bundles/af-core/src/test/resources/form/componentswithrule/test-content.json

CQ-4349893 Bringing validationStatus property from sling model

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/editor/js/editDialog.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/numberinput.html

Refactored the exclude min and max checkboxes to `excludeMinimumCheck` and `excludeMaximumCheck` as the `exclusiveMinimum` and `exclusiveMaximum` need to be of type `Long` to conform to the model.
Now these `Long` type fields are dynamically created when the respective checkbox is checked, which allows for the validations on AF2 web runtime to work properly. 
https://jira.corp.adobe.com/browse/CQ-4348911

CQ-4348911 Exclude minimum and maximum value functionality fix for number input component.

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/services/formsportal/OperationManagerImpl.java

CQ-4349590 Fixed "unsupported type java.util.Map" error in Forms Portal

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/clientlibs/editor/js/editDialog.js

Added fallback for options display text when empty; now defaults to data value for dropdown, checkbox and radiobutton
https://jira.corp.adobe.com/browse/CQ-4349509

CQ-4349509 - Display Value for options becomes empty in dropdown/radiobutton/checkbox if not defined

---

examples/ui.apps/pom.xml
ui.af.apps/pom.xml

Correct dependency range of apps package

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/js/fileinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.frontend/src/view/FormField.js
ui.frontend/src/view/FormFieldBase.js
ui.frontend/src/view/FormPanel.js
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/specs/text/text.runtime.spec.js

CQ-4350343 Minimize API exposure in ui.frontend library

---

ui.frontend/package.json

updating core to version 0.22.18

---

.circleci/config.yml

Moving from azul to open jdk

---

.devcontainer/devcontainer.json
README.md

Adding support for github codespaces

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/_cq_dialog/.content.xml

[CQ-4349734](https://jira.corp.adobe.com/browse/CQ-4349734)

[CQ-4349734] Hide show upload comments in Edit Dialog (File Attachment)

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/PanelContainerImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/PanelContainerImplTest.java
bundles/af-core/src/test/resources/form/panelcontainer/exporter-panelcontainer.json
bundles/af-core/src/test/resources/form/panelcontainer/test-content.json

CQ-4349966 [Panel] - DoR property: In pagination, Overflow is not working in DoR

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/js/textinputview.js
ui.frontend/src/view/FormFieldBase.js

avoid initialising model with empty value

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/css/formcontainerview.css

CQ-4350589 Fix Hide Component

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/README.md
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/README.md
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/editor/js/panelcontainer.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/README.md
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/_cq_dialog/.content.xml
ui.tests/test-module/specs/accordion/accordion.authoring.spec.js
ui.tests/test-module/specs/panelcontainer/panelcontainer.authoring.spec.js
ui.tests/test-module/specs/tabsontop/tabsontop.authoring.spec.js
ui.tests/test-module/specs/wizard/wizard.authoring.spec.js

CQ-4350963 Hiding repeat settings, till full repeatability is supported.

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js.txt
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/copypastehook.js
ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

CQ-4348729 Pasted component name is same as the copied component name

---

ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

CQ-4348729 Fix test of copy paste component

---

ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

CQ-4348729 Test fix for copy paste component.

---

ui.frontend/__tests__/guidebridge.test.js
ui.frontend/__tests__/resources/form.json
ui.frontend/src/GuideBridge.js

CQ-4349886 GuideBridge API to hide buttons

---

all/pom.xml
bundles/af-core/pom.xml
bundles/core/pom.xml
examples/all/pom.xml
examples/pom.xml
examples/ui.apps/pom.xml
examples/ui.content/pom.xml
it/apps/pom.xml
it/config/pom.xml
it/content/pom.xml
it/core/pom.xml
parent/pom.xml
pom.xml
ui.af.apps/pom.xml
ui.apps/pom.xml
ui.frontend/pom.xml
ui.tests/pom.xml

update version to 2.0.100-SNAPSHOT

---

it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/actions/submit/customsubmit/.content.xml
it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/actions/submit/customsubmit/basic/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/actions/submit/customsubmit/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/actions/submit/customsubmit/basic/.content.xml
ui.tests/test-module/specs/actions/submit/submit.runtime.spec.js

Test Parity: Custom Submit Cypress tests

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/actions/reset/v1/reset/README.md
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/actions/submit/v1/submit/README.md

README.md for OOTB Submit and Reset buttons

Reset and Submit button README.md files

---

ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

CQ-4348729 skip flaky test

---

ui.frontend/src/HTTPAPILayer.js

CQ-4351228 Support for locale during fetch of form model definition

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js

CQ-4351091 Support key events in datepicker widget

---

ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/package-lock.json
ui.tests/test-module/package.json

@trivial Fixing flaky test

---

ui.tests/test-module/libs/plugins/index.js
ui.tests/test-module/package-lock.json
ui.tests/test-module/package.json

@trivial Adding support to dump logs to debug for ci

---

bundles/af-core/pom.xml
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/Base.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/BaseConstraint.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/ContainerConstraint.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/Field.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FileConstraint.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormComponent.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormMetaData.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormatConstraint.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/NumberConstraint.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/OptionsConstraint.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/StringConstraint.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
bundles/core/pom.xml
it/core/pom.xml
parent/pom.xml

@trivial Moving to latest aem forms sdk

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextImpl.java

[CQ-4351334](https://jira.corp.adobe.com/browse/CQ-4351334)

adding translate function for value property for text static component

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/numberinput/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputwidget.js
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/libs/support/index.js
ui.tests/test-module/specs/numberinput/numberinput.authoring.spec.js
ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
ui.tests/test-module/specs/tabsontop/tabsontop.authoring.spec.js

@trivial support for formatters in numeric input

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/clientlibs/editor/utils/utils.js

CQ-4351048 Fix workflow submit action UI for forms container in Sites

---

ui.tests/test-module/specs/accordion/accordion.authoring.spec.js
ui.tests/test-module/specs/aemformcontainer.spec.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.authoring.spec.js
ui.tests/test-module/specs/portal/draftsnsubmissionscomponent.spec.js
ui.tests/test-module/specs/telephoneinput/telephoneinput.authoring.spec.js
ui.tests/test-module/specs/wizard/wizard.authoring.spec.js

@trivial cleaning test collateral before test retry

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/button/basic/.content.xml
ui.frontend/pom.xml
ui.frontend/src/customFunctions.js
ui.tests/pom.xml
ui.tests/test-module/specs/button/button.runtime.spec.js

- also bumped node version as per archetype @review @vdua
DOD(Yes)

CQ-4351707 Added support for navigateTo

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/ruleeditorhook.js

CQ-4351561  Add zIndex to rule editor fram

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/panelcontainer/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/runtime/js/panelcontainerview.js
ui.frontend/src/utils.js
ui.frontend/src/view/FormField.js
ui.frontend/src/view/InstanceManager.js
ui.tests/test-module/specs/panelcontainer/panelcontainer.runtime.spec.js

CQ-4351518 Duplicate ids, when panel is initialised with minOccur.

---

all/pom.xml
bundles/af-core/pom.xml
bundles/core/pom.xml
examples/all/pom.xml
examples/pom.xml
examples/ui.apps/pom.xml
examples/ui.content/pom.xml
it/apps/pom.xml
it/config/pom.xml
it/content/pom.xml
it/core/pom.xml
parent/pom.xml
pom.xml
ui.af.apps/pom.xml
ui.apps/pom.xml
ui.frontend/pom.xml
ui.tests/pom.xml

@Review : @nitigupt @rismehta
Backported core component codes to 6.5

CQ-4348870 Forms Core Component backport to 6.5

---

pom.xml

@trivial Fixing release

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/clientlibs/editor/utils/utils.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/clientlibs/editor/js/editDialog.js
ui.tests/test-module/specs/formcontainer.spec.js

CQ-4351048 Register clientlibs for form submit actions sub dialog in Sites page

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/ruleeditorhook.js
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

CQ-4350640 Fix Sites content tree while opening rule editor

---

bundles/af-core/pom.xml
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/package-info.java
bundles/core/pom.xml
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/aemform/package-info.java
bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/formsportal/package-info.java
examples/core/pom.xml
examples/ui.apps/pom.xml
parent/pom.xml
ui.af.apps/pom.xml

fixed bundles issues

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/css.txt
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/replacehook.js

updated license and fieldType value

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/checkboxgroup.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/editor/js/editDialog.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/js/fileinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.frontend/src/view/FormFieldBase.js

Feature to add a BEM modifier class to the widget of each core component based the existence of a value in it.
Also changed checkbox widget's class to align with radiobutton's current format. And a bug with checkbox's `checked=` field showing `undefined` due to incorrect usage of constant
[CQ-4351811](https://jira.corp.adobe.com/browse/CQ-4351811)
[CQ-4351956](https://jira.corp.adobe.com/browse/CQ-4351956)

CQ-4351811 & CQ-4351956 - Addition of empty/filled class based on field content AND File Attachment dialog fix

---

.circleci/ci/it-tests.js
.circleci/config.yml
.circleci/settings.xml

@trivial adding cypress test cases for release/650

---

README.md
VERSIONS.md

@trivial update versions and README

---

.circleci/ci/it-tests.js
.circleci/config.yml
.circleci/settings.xml
ui.tests/test-module/libs/support/index.js

@releng enable test run against latest far

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java

The fix was tested and manually validated.

Fixed translations not getting picked up in 6.5 core-components

---

.circleci/ci/it-tests.js
.circleci/config.yml

@trivial Moving to latest load

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/ruleeditorhook.js

Rule editor issue with jee server

---

ui.tests/test-module/libs/support/commands.js

@trivial Fixing test cases for release/650

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

[Backport] Fix redirect Thankyou Message for contextRoot

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/clientlibs/editorhook/js/EditListeners.js
ui.tests/test-module/libs/support/index.js
ui.tests/test-module/specs/aemformcontainer.spec.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.authoring.spec.js
ui.tests/test-module/specs/datepicker/datepicker.authoring.spec.js
ui.tests/test-module/specs/dropdown/dropdown.authoring.spec.js
ui.tests/test-module/specs/numberinput/numberinput.authoring.spec.js
ui.tests/test-module/specs/portal/formsportallinkcomponent.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.authoring.spec.js

@trivial Fixing test cases

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/container/_cq_template.xml

Adding fd:version in form container proxy component

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.tests/test-module/specs/wizard/wizard.authoring.spec.js

FORMS-3589 Enable responsiveness for forms guide container component.

---

README.md

Issue 491 update readme with list of components

---

ui.frontend/package.json

@trivial Upgrade af core

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/container/.content.xml
ui.tests/test-module/libs/support/index.js
ui.tests/test-module/specs/formcontainer.spec.js

FORMS-3571 Supporting Adaptive Form container in sites editor

---

ui.frontend/src/GuideBridge.js

#523 null check on guidebridge getFormModel

---

bundles/af-core/pom.xml
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/Container.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
bundles/af-core/src/test/resources/form/panel/exporter-array-panel.json
bundles/af-core/src/test/resources/form/panel/exporter-bound-panel.json
bundles/af-core/src/test/resources/form/panel/exporter-panel.json
bundles/af-core/src/test/resources/form/panel/exporter-rules-panel.json
bundles/af-core/src/test/resources/form/panelcontainer/exporter-array-panelcontainer.json
bundles/af-core/src/test/resources/form/panelcontainer/exporter-panelcontainer-customized.json
bundles/af-core/src/test/resources/form/panelcontainer/exporter-panelcontainer.json
bundles/af-core/src/test/resources/form/panelcontainer/exporter-rules-panelcontainer.json
bundles/af-core/src/test/resources/schema/0.11.0-Pre/adaptive-form.schema.json
bundles/core/pom.xml
examples/core/pom.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/ruleeditorhook.js
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/pom.xml

Merge spa branch to dev

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/js/fileinputview.js

[FORMS-7476] fix file attachment issue

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/fileinput/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/js/fileinputwidget.js
ui.frontend/package-lock.json
ui.tests/test-module/specs/fileinput/fileinput.runtime.spec.js

https://jira.corp.adobe.com/browse/FORMS-7152

[FORMS-7152] - File attachment Prefill bug with tests

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractComponentImpl.java
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/button.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/checkboxgroup.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/datepicker.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/dropdown.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/emailinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/fileinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/numberinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/radiobutton.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/telephoneinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/text.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/textinput.html

Fix id miss-match for components in AEM forms container (Approach 2)

---

bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormContainerImplTest.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

@trivial Adding missing test cases

---

README.md
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/aemform/.content.xml
examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml
examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/core-content/aemform/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/README.md
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/_cq_dialog/.content.xml
ui.tests/test-module/specs/aemformcontainer.spec.js

FORMS-7407 Renaming AEM Forms Container to Adaptive Forms - Embed

---

.circleci/config.yml

Updating to latest released AEM SDK

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
ui.tests/test-module/specs/actions/submit/submit.runtime.spec.js

FORMS-7960 Fixed Redirect Spoof for AEM Internal Page OOTB

---

.circleci/ci/build.js
.circleci/ci/it-tests.js
.circleci/config.yml
examples/all/pom.xml
ui.frontend/pom.xml
ui.tests/pom.xml
ui.tests/test-module/README.md
ui.tests/test-module/libs/support/index.js
ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

FORMS-7906 Test cases for expression editor of field inside site container

---

.circleci/ci/it-tests.js

@trivial re-try it-test run

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/PanelImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFieldImpl.java
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datalayer/basic/.content.xml

Forms-5839 dev fix - removing title from json of all the component except formConatiner.

---

ui.tests/test-module/specs/databinding/databinding.authoring.spec.js
ui.tests/test-module/specs/panelcontainer/panelcontainer.authoring.spec.js
ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

Forms 8218 650 trivial, flaky authoring test cases fix

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

Add getParentPagePath in forms Container

---

ui.frontend/package-lock.json
ui.frontend/package.json

- Support for integer type in number
- Support for disable form
- support for add/remove instance custom functions
- Support for custom functions

@releng updating af-core version

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/accordion/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html

Reference:- https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md

[FORMS-8103] added changes to add tag on form container so that iframe resizer third party can find the end of the form to determine height

---

ui.tests/test-module/specs/actions/disable/disable.runtime.spec.js

Added disabled form test case

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/_cq_editConfig.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/clientlibs/editorhook/js/EditListeners.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/formcontainer.html

FORMS-8848 Remove creating AF from embed component via wizard

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/aemform.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/formcontainer.html
ui.tests/test-module/specs/actions/disable/disable.runtime.spec.js

dev to master merge

---

it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-locale/css.txt
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/css.txt

Fixing the copyright comment in css.txt files

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/checkboxgroup.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/datepicker.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/fileinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/numberinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/radiobutton.html

[FORMS-8706] add required attribute

---

.circleci/ci/it-tests.js
.circleci/config.yml
jsdocs/jsdoc.conf.json
jsdocs/package-lock.json
jsdocs/package.json
jsdocs/pom.xml
jsdocs/resources/copyright/README.md
jsdocs/resources/css/site.cosmo.css
pom.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/clientlibs/editor/utils/utils.js
ui.frontend/src/utils.js
ui.frontend/src/view/FormFieldBase.js
ui.tests/test-module/specs/formcontainer.spec.js
ui.tests/test-module/specs/numberinput/numberinput.authoring.spec.js
ui.tests/test-module/specs/tabsontop/tabsontop.authoring.spec.js

- Included documentation of view/edit dialogs/ui.frontend @review @vdua
DOD(yes)

FORMS-8092 Adding jsdocs framework for core components

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/text/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/clientlibs/site/js/textview.js
ui.tests/test-module/specs/text/text.runtime.spec.js

https://jira.corp.adobe.com/browse/FORMS-8029

FORMS-8029 - Static Text Core Component should update value via Rules

---

ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/specs/actions/render/render_with_openapi.spec.js

FORMS-8952 Test case to test list forms and model api

---

.circleci/ci/accessibility-axe.js
.circleci/ci/accessibilityConfig.json
.circleci/ci/ci.js
.circleci/ci/it-tests.js
.circleci/ci/lighthouse.js
.circleci/ci/lighthouseConfig.js
.circleci/ci/lighthouseConfig.json
.circleci/ci/stop-cq.js
.circleci/config.yml

Forms 7782 lhs axe

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/common.less
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/resources/tick.svg
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/resources/tick_hover.svg
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/verticaltabs.less
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/index.less

FORMS-8971 Canvas Theme for vertical tabs Example

---

.circleci/ci/accessibility-axe.js
.circleci/ci/ci.js
.circleci/ci/lighthouse.js

FORMS-8959 | enabled git pr comment

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/draftsandsubmissions/v1/draftsandsubmissions/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v1/link/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v2/link/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/searchlister/v1/searchlister/_cq_dialog/.content.xml

[FORMS-7468](https://jira.corp.adobe.com/browse/FORMS-7468)

[FORMS-7468]: Update help text of drafts and submission, link, search and lister, email, telephone

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datalayer/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/datalayer/datalayer.js
ui.tests/test-module/specs/datalayer/dataLayer.runtime.spec.js

FORMS-8785 - Bug Fix - Use guideBridge to get root panel title instead of datalayer

FORMS-8812 - Forms in sites - Multiple form support for DataLayer

---

.circleci/config.yml

Failing release if jsdocs deployment failed

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/_cq_dialog/.content.xml

FORMS-8828 items tab in edit dialog of wizard and vertical tabs

---

.circleci/config.yml
parent/pom.xml

[Release] update cq quickstart version and wcm core component version

---

.circleci/ci/accessibility-axe.js
.circleci/ci/ci.js
.circleci/ci/lighthouse.js
.circleci/config.yml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datalayer/basic/.content.xml
parent/pom.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/datalayer/datalayer.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/draftsandsubmissions/v1/draftsandsubmissions/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v1/link/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v2/link/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/searchlister/v1/searchlister/_cq_dialog/.content.xml
ui.tests/test-module/specs/datalayer/dataLayer.runtime.spec.js

Dev 2 master 7 june23

---

.circleci/ci/accessibility-axe.js
.circleci/ci/ci.js
.circleci/ci/lighthouse.js
.circleci/config.yml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datalayer/basic/.content.xml
parent/pom.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/datalayer/datalayer.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/_cq_dialog/.content.xml
ui.tests/test-module/specs/datalayer/dataLayer.runtime.spec.js

Master 2 650 7 jun23

---

.circleci/config.yml

Fixing js docs job

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js

- test cases already exist
@review @vdua
DOD(yes)

FORMS-2998 using model edit and display value API's for date picker

---

.circleci/config.yml

Fixing release job

---

.circleci/config.yml
ui.frontend/package.json
ui.frontend/src/view/FormFieldBase.js
ui.tests/test-module/specs/actions/submit/submit.runtime.spec.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.spec.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
ui.tests/test-module/specs/dropdown/dropdown.runtime.spec.js
ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js
ui.tests/test-module/specs/textinput/textinput.runtime.spec.js

Updating af-core to 0.22.45

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/accordion/nestedrepeatability/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/accordion.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/site/js/accordionview.js
ui.frontend/src/utils.js
ui.frontend/src/view/FormPanel.js
ui.frontend/src/view/InstanceManager.js
ui.tests/test-module/specs/accordion/accordion.repeatability.runtime.spec.js

[FORMS-8152] add add /remove button for repeatable accrodion item

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextInputImplTest.java
bundles/af-core/src/test/resources/form/textinput/exporter-textinput-blank-dataref.json
bundles/af-core/src/test/resources/form/textinput/test-content.json

Forms 9483

---

.circleci/config.yml
README.md
parent/pom.xml
ui.frontend/package.json

[Releng] Updating to AEM 12441 release

---

jsdocs/jsdoc.conf.json
ui.frontend/src/FormData.js
ui.frontend/src/GuideBridge.js
ui.frontend/src/HTTPAPILayer.js
ui.frontend/src/LanguageUtils.js
ui.frontend/src/Response.js
ui.frontend/src/constants.js
ui.frontend/src/customFunctions.js
ui.frontend/src/index.js
ui.frontend/src/utils.js
ui.frontend/src/view/FormContainer.js
ui.frontend/src/view/FormField.js
ui.frontend/src/view/FormFieldBase.js
ui.frontend/src/view/FormPanel.js
ui.frontend/src/view/FormTabs.js
ui.frontend/src/view/InstanceManager.js
ui.frontend/src/view/index.js

FORMS-8092 JS Docs

---

ui.tests/test-module/specs/textinput/textinput.authoring.spec.js

FORMS-9488: uncomment textinput authoring rule editor test

---

ui.frontend/src/view/FormFieldBase.js
ui.frontend/src/view/FormPanel.js
ui.frontend/src/view/InstanceManager.js
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/specs/accordion/accordion.minoccur.spec.js
ui.tests/test-module/specs/accordion/accordion.repeatability.runtime.spec.js
ui.tests/test-module/specs/accordion/accordion.runtime.spec.js
ui.tests/test-module/specs/textinput/textinput.runtime.spec.js
ui.tests/test-module/specs/wizard/wizard.runtime.repeatability.spec.js
ui.tests/test-module/specs/wizard/wizard.runtime.spec.js

- added support to fail test if console errors are present @review @vdua
DOD(Yes)

FORMS-9702 Fixing the update property in view layer

---

.circleci/config.yml
it/content/src/main/content/jcr_root/conf/core-components-it/samples/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/samples/accessibility/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/samples/accessibility/_sling_configs/.content.xml
it/content/src/main/content/jcr_root/conf/core-components-it/samples/accessibility/_sling_configs/_rep_policy.xml
it/content/src/main/content/jcr_root/conf/core-components-it/samples/accessibility/_sling_configs/com.adobe.cq.wcm.core.components.config.HtmlPageItemsConfig/.content.xml

Upgraded docker machine hardware to improve lighthouse performance.

---

.circleci/config.yml

Releng moving to 6.5.18 load4 release

---

.circleci/ci/it-tests.js

[Releng] Adding toggle impl bundle during test execution

---

.circleci/config.yml

Releng: Fixing release

---

.circleci/config.yml

Fix circle CI build failing at install chromedriver step

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/actions/submit/external/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.tests/test-module/specs/actions/submit/submit.runtime.spec.js

FORMS-9888 Thank you page URL pointing to an external page is broken for AF2.

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractComponentImpl.java
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragment/v1/fragment/clientlibs/editorhook/js/fragmenthook.js
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/formcontainer.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/removeattribute.js

Fix core component rendition in sites

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java

FORMS-9917 Submit successfull event is not working

---

ui.frontend/package.json

Releng updating forms core version

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImpl.java
ui.frontend/package-lock.json

JIRA: [FORMS-9967](https://jira.corp.adobe.com/browse/FORMS-9967)

adding translate function for altText property for image static component

---

bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FragmentImplTest.java
bundles/af-core/src/test/resources/form/fragment/test-content.json
it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/fragment/test-fragment/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/clientlibs/editor/js/editDialog.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragmentcontainer/v1/fragmentcontainer/_cq_dialog/.content.xml
ui.tests/test-module/libs/commons/formsConstants.js
ui.tests/test-module/specs/fragment/fragment.authoring.spec.js
ui.tests/test-module/specs/fragmentcontainer.spec.js

Tests related to Fragment support

---

bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FragmentImplTest.java
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragment/v1/fragment/README.md

Fragment review comment

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/textinput/basic/.content.xml
ui.frontend/package.json
ui.tests/test-module/specs/aemEmbedContainer/aemEmbedContainer.runtime.spec.js
ui.tests/test-module/specs/textinput/textinput.runtime.spec.js

Releng updating forms core version to 0.22.55

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/recaptcha/v1/recaptcha/_cq_template.xml

FORMS-10133-Mark required true in recaptcha template

---

ui.frontend/package.json

@releng updating af core version

---

ui.frontend/src/constants.js
ui.frontend/src/view/FormFieldBase.js
ui.tests/test-module/specs/guideBridge.spec.js

FORMS-10186 Fixing GuideBridge events

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/textinput/focus/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
ui.frontend/package-lock.json
ui.frontend/package.json
ui.frontend/src/view/FormContainer.js
ui.tests/test-module/specs/textinput/textinput.runtime.spec.js

[FORMS-10243] fix setFocus issue

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datepicker/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

Fixed edit/diplay values getting set in datepicker model

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
bundles/af-core/src/test/resources/form/formcontainer/test-content.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
ui.frontend/src/utils.js

FORMS-10402 Optimizing AF prefill

---

.circleci/ci/it-tests.js
.circleci/config.yml
ui.tests/pom.xml

[CI] Re-run only test failures

---

.circleci/ci/it-tests.js
.circleci/config.yml
.gitignore
ui.tests/README.md
ui.tests/pom.xml
ui.tests/test-module/cypress.json
ui.tests/test-module/package-lock.json
ui.tests/test-module/package.json

[CI] Fixing cypress test reporter

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/clientlibs/editor/js/editDialog.js

FORMS-9330 correct selectors in edit dialog

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormClientLibManagerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormClientLibManager.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/form/FormClientLibManagerImplTest.java

Incorporating review comments.

---

bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/form/FormClientLibManagerImplTest.java

Adding test.

---

.circleci/config.yml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/componentutils.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/copypastehook.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/dorhook.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/replacehook.js

@releng adding strict mode

---

.circleci/config.yml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/de.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/en.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/es.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/fr.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/it.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/ja.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/ko-kr.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/pt-br.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/zh-cn.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/zh-tw.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/componentutils.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/copypastehook.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/dorhook.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/replacehook.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/css/datepickerwidget.css
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.localisation.spec.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

Dev to master30aug

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js

Fix inputted date not reflecting in calendar

---

.circleci/ci/ci.js
.circleci/ci/it-tests.js

FORMS-9959 Test infrastructure changes to include core components in far

---

.github/workflows/sync-pr.yml
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/Utils.java
bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainer.json
bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-aem-allowed-components.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-aem-responsive-grid-properties.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-container-dor-properties.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-data-constraints.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-data-layer.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-defaults.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-dor-properties.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-enum-name.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-events.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-label.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-properties.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-property-restrictions.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-sign-properties.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form-signer-properties.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/adaptive-form.schema.json
bundles/af-core/src/test/resources/schema/0.12.1/form.json

@releng moving to 0.12.1 schema

---

ui.frontend/package.json
ui.frontend/src/GuideBridge.js
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/libs/support/index.js
ui.tests/test-module/specs/guideBridge.spec.js

- bumping af core version @review @vdua
DOD(Yes)

FORMS-10718 GuideBridge resolveNode API

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/actions/submit/customsubmit/basicwithrequestparameters/.content.xml
it/core/src/main/java/com/adobe/cq/forms/core/components/it/service/CustomAFSubmitService.java
ui.tests/test-module/specs/actions/submit/submit.runtime.spec.js

test cases for custom submit action with redirect parameters

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextInputImplTest.java
bundles/af-core/src/test/resources/form/textinput/exporter-textinput-blank-validationExpression.json
bundles/af-core/src/test/resources/form/textinput/test-content.json

Before model.json
``` json
{
"id": "textinput-b6b9c223e7",
"fieldType": "text-input",
"name": "textinput1693323005360",
"type": "string",
"validationExpression": "",
"label": {
"value": "Text Input"
},
"events": {
"custom:setProperty": [
"$event.payload"
]
},
"properties": {
"fd:dor": {
"dorExclusion": false
},
"fd:path": "[/content/forms/af/1001/jcr:content/guideContainer/textinput](http://localhost:4502/content/forms/af/1001/jcr:content/guideContainer/textinput)"
},
":type": "forms-components-examples/components/form/textinput"
}
```
After the change model json
``` json
{
"id": "textinput-b6b9c223e7",
"fieldType": "text-input",
"name": "textinput1693323005360",
"type": "string",
"label": {
"value": "Text Input"
},
"events": {
"custom:setProperty": [
"$event.payload"
]
},
"properties": { …
```

Forms  9492:  removing validationExpression empty string from the json model, after validation rule deletion

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/js.txt
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/clientlibs/runtime/formapp/css.txt
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/clientlibs/runtime/formapp/js.txt
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/clientlibs/site/css.txt

@releng: fixing client library compilation issue

---

.github/workflows/spec-validate-pr.yml

Spec validation during PR

---

.circleci/ci/lighthouse.js
.circleci/config.yml
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/libs/support/index.js

parallel test execution

---

.circleci/ci/it-tests.js
.circleci/config.yml
ui.tests/pom.xml

Releng: adding release 6.5.18.0 and latest snapshot test run

---

.circleci/ci/it-tests.js
.circleci/config.yml
parent/pom.xml
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/specs/accordion/accordion.authoring.spec.js
ui.tests/test-module/specs/checkbox/checkbox.authoring.spec.js
ui.tests/test-module/specs/emailinput/emailinput.authoring.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.authoring.spec.js
ui.tests/test-module/specs/workflow.spec.js

Releng moving to latest cloud ready quickstart

---

.circleci/ci/accessibility-axe.js
.circleci/ci/accessibilityConfig.json
.circleci/ci/it-tests.js
.circleci/config.yml

Forms 10956 axe

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/dropdown/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/checkbox.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/clientlibs/site/js/checkboxview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/checkboxgroup.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/datepicker.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/dropdown.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/emailinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/fileinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/numberinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/radiobutton.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/recaptcha/v1/recaptcha/recaptcha.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/telephoneinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/textinput.html
ui.frontend/src/constants.js
ui.frontend/src/view/FormFieldBase.js
ui.frontend/src/view/FormPanel.js
ui.tests/test-module/libs/commons/localeDataSets.js
ui.tests/test-module/specs/checkbox/checkbox.runtime.spec.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.spec.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
ui.tests/test-module/specs/dropdown/dropdown.runtime.spec.js
ui.tests/test-module/specs/emailinput/emailinput.runtime.spec.js
ui.tests/test-module/specs/fileinput/fileinput.runtime.spec.js
ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js
ui.tests/test-module/specs/telephoneinput/telephoneinput.runtime.spec.js
ui.tests/test-module/specs/textinput/textinput.runtime.spec.js

[FORMS-10944] update filled/empty class

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/css/datepickerwidget.css
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.localisation.spec.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

Forms 10419: clear option bug fix for Date Picker

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js

RTL direction fix

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html

change direction of form based on locale

---

it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/tabsontop/focusWithRule/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/tabsontop/focusWithRule/.content.xml
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/specs/tabsontop/tabsontop.runtime.spec.js

* Update af-core version
* Fixed test cases

Dev to Master 

---

.circleci/config.yml

Fixing versions.md script

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/iframe.html
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/iframe.html

lang attribute set on html instead of head element to comply with accessibility guidelines. lang value is set to form locale, and default value is en.

FORMS-11162 - Accessibility Issue - Forms iframe head tag issue

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/pageheader/_cq_template.xml

use wcm image for integration testing

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v1/link/clientlibs/editor/js/linkcomponent.js

FORMS-11128 Localized Add Item string

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/checkbox.less
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/common.less
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/termsandconditions.less
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/index.less

Example Canvas Themes for CheckbBox and TermsAndConditions

---

ui.af.apps/pom.xml

unhide checkbox, termsandconditions, switch

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/common.less
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/adaptive-form/switch.less
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/styles/components/index.less
examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/adaptive-form/switch/.content.xml

added theme for aem corecomponents.dev

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/pageheader/v1/pageheader/_cq_template.xml

replaced foundation image and text with wcm core components

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/checkboxgroup/focustest/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/radiobutton/focustest/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/css/checkboxgroupview.css
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/css/radiobuttonview.css
ui.frontend/src/view/FormField.js
ui.frontend/src/view/FormFieldBase.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js

Setfocus issuefixes

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormContainerTest.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js

[RTL] Change direction of content in forms at runtime

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/clientlibs/runtime/js/termsandconditionsview.js
ui.tests/test-module/specs/termsandconditions/tnc.runtime.spec.js

tnc fix for approval checkbox not getting sent in submission

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/clientlibs/runtime/js/termsandconditionsview.js
ui.tests/test-module/specs/termsandconditions/tnc.runtime.spec.js

Dev To Master

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
it/core/src/main/java/com/adobe/cq/forms/core/components/it/service/CustomAFSubmitService.java
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.frontend/src/HTTPAPILayer.js
ui.frontend/src/utils.js

Dev to master 3 11

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragment/v1/fragment/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/_cq_dialog/.content.xml

[FORMS-11514]: Update help links

---

.circleci/ci/it-tests.js
.circleci/config.yml
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
ui.tests/test-module/libs/support/functions.js

Updating package-info for 6.5.18 to pass

---

it/core/src/main/java/com/adobe/cq/forms/core/components/it/service/CustomAFSubmitService.java

Updating submission error sample

---

.circleci/config.yml
.github/workflows/spec-validate-pr.yml
parent/pom.xml
ui.tests/test-module/specs/workflow.spec.js

@releng moving to latest aem image

---

.circleci/config.yml
.github/workflows/spec-validate-pr.yml
it/core/src/main/java/com/adobe/cq/forms/core/components/it/service/CustomAFSubmitService.java
parent/pom.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragment/v1/fragment/_cq_dialog/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/_cq_dialog/.content.xml
ui.tests/test-module/specs/workflow.spec.js

Dev master 06 11

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java

Fixing package version

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/css/replacehook.css

fixed truncating replace dialog localized search input

---

bundles/af-core/pom.xml
bundles/core/pom.xml
parent/pom.xml
ui.af.apps/pom.xml
ui.apps/pom.xml

update version of impsort-maven-plugin

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/README.md
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/checkbox.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/_cq_dialog/.content.xml
ui.tests/test-module/specs/button/button.authoring.spec.js
ui.tests/test-module/specs/checkbox/checkbox.authoring.spec.js
ui.tests/test-module/specs/image/image.authoring.spec.js
ui.tests/test-module/specs/text/text.authoring.spec.js

removed readonly and updated tests

---

ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/specs/accordion/accordion.authoring.spec.js
ui.tests/test-module/specs/checkbox/checkbox.authoring.spec.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.authoring.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.authoring.spec.js
ui.tests/test-module/specs/replaceaction/replacelayout-container.authoring.spec.js
ui.tests/test-module/specs/replaceaction/replacelayout-sites.authoring.spec.js
ui.tests/test-module/specs/telephoneinput/telephoneinput.authoring.spec.js

fixed test cases

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/radiobutton/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js

Fixed radiobutton with boolean save value not selected in first click.

---

ui.tests/test-module/specs/actions/customProperties/customProperties.spec.js

650 failure fix

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/_cq_design_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/_cq_dialog/.content.xml

style tab and custom properties tab not working on tnc component fixed

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/datepicker.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/emailinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/numberinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/tabsontop.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/telephoneinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/textinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/verticaltabs.html

changed direction attribute for fillable fields

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html

Added support of dir on container

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/datepicker.html

rtl date input fixes

---

.circleci/ci/ci.js
.circleci/ci/it-tests.js
.circleci/config.yml
.circleci/docker-compose.yml
.gitignore
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/actions/submit/external/.content.xml
jsdocs/pom.xml
ui.frontend/pom.xml
ui.tests/pom.xml
ui.tests/test-module/libs/support/commands.js
ui.tests/test-module/libs/support/index.js
ui.tests/test-module/specs/accordion/accordion.authoring.spec.js
ui.tests/test-module/specs/actions/submit/submit.runtime.spec.js
ui.tests/test-module/specs/databinding/databinding.authoring.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.authoring.spec.js
ui.tests/test-module/specs/switch/switch.authoring.spec.js

Enabling dor service docker for it test

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v2/fileinput/_cq_dialog/.content.xml
ui.tests/test-module/specs/fileinput/fileinput.authoring.spec.js

Fil input v2 dialog fix

---

.circleci/ci/build.js
.circleci/config.yml
pom.xml
ui.frontend/pom.xml
ui.tests/pom.xml
ui.tests/test-module/specs/checkbox/checkbox.authoring.spec.js
ui.tests/test-module/specs/replaceaction/replacelayout-container.authoring.spec.js

Manually download and cache Node.js distribution on CI

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.tests/test-module/specs/formcontainer.spec.js

Adding this for parity with AF1.

FORMS-12555 Adding post method to the adaptive form container.

---

ui.tests/test-module/libs/support/commands.js

Context path changes

---

.circleci/ci/it-tests.js
.circleci/config.yml
ui.tests/pom.xml
ui.tests/test-module/libs/support/commands.js

Enabling context path in test

---

.circleci/config.yml

Adding atleast once guarantee while creating github release notes

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v2/fileinput/clientlibs/site/css/fileinputview.css
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v2/fileinput/clientlibs/site/js/fileinputwidget.js

file input highlight drop area

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/searchlister/v1/searchlister/searchlister.html

https://jira.corp.adobe.com/browse/FORMS-12679

FORMS-12679: Strings is unlocalized in "Search and Lister" Component in "Preview" mode

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/_cq_editConfig.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/_cq_editConfig.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/_cq_editConfig.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/_cq_editConfig.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/_cq_editConfig.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/_cq_editConfig.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/_cq_editConfig.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/js/wizardview.js

Support for versioning and annotation

---

ui.tests/test-module/cypress.json

Adding auto retry of failed test in 650 due to flakiness

---

.circleci/docker-compose.yml

Updating aem base image version

---

.circleci/docker-compose.yml

Dev to master 6 feb

---

.circleci/config.yml
ui.tests/test-module/cypress.json
ui.tests/test-module/specs/contentfragment/contentfragment.authoring.spec.js
ui.tests/test-module/specs/emailinput/emailinput.authoring.spec.js

Fixing flaky test and release job

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
bundles/af-core/src/test/resources/form/formcontainer/test-content.json

FORMS-12700 Adding spec version as jcr property

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/datalayer/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v2/fileinput/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/runtime/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/recaptcha/v1/recaptcha/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/switch/v1/switch/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/.content.xml

Adding allowProxy to runtime client library

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/recaptcha/v1/recaptcha/clientlibs/site/js/recaptchawidget.js

reCAPTCHA widget localization issue
https://jira.corp.adobe.com/browse/FORMS-13075

FORMS-13075 | recaptcha localization issue

---

ui.frontend/jest.config.js
ui.frontend/package-lock.json
ui.frontend/package.json
ui.frontend/src/customFunctions.js

Adding af-custom-function dependency

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/container/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/md.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/page/v1/page/body.html

Adding rendition for EDS

---

.circleci/ci/accessibility-axe.js

Adding rules for accessibility A, AA and AAA tags.

---

.circleci/ci/accessibility-axe.js
.circleci/ci/accessibilityConfig.json

Adding accessibility standards and exceptions.

---

it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
ui.tests/test-module/specs/rum/rum.runtime.spec.js

Fixing rum test as per new FT

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.frontend/src/view/FormFieldBase.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js

Fixed updateRequired for checkboxgroup and radiobutton

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
bundles/af-core/src/test/resources/form/formcontainer/test-page-content.json

FORMS-13356 Fixing context path addition in thank you page

---

all/pom.xml
bundles/af-core/pom.xml
bundles/core/pom.xml
examples/all/pom.xml
examples/core/pom.xml
examples/pom.xml
examples/ui.apps/pom.xml
examples/ui.content/pom.xml
it/apps/pom.xml
it/config/pom.xml
it/content/pom.xml
it/core/pom.xml
jsdocs/pom.xml
parent/pom.xml
pom.xml
ui.af.apps/pom.xml
ui.apps/pom.xml
ui.frontend/pom.xml
ui.tests/pom.xml

upgrading the major version to 3.x.x

---

it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/datepicker/datepickerlayoutissue/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datepicker/datepickerlayoutissue/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.layout.spec.js

date picker layout issue

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/README.md
ui.frontend/src/HTTPAPILayer.js
ui.tests/test-module/specs/prefill/customprefill.spec.js

FORMS-13753 Fixing regression related to dataRef parameter

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/_cq_dialog/.content.xml

[FORMS-13484](https://jira.corp.adobe.com/browse/FORMS-13484)

FORMS-13484: Update the help link for Embed (v2)

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js

FORMS-13829 Drop Down View not getting updated, even if model is updated.

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/Utils.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-aem-allowed-components.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-aem-responsive-grid-properties.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-container-dor-properties.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-data-constraints.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-data-layer.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-defaults.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-dor-properties.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-events.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-label.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-properties.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-property-restrictions.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-sign-properties.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form-signer-properties.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/adaptive-form.schema.json
bundles/af-core/src/test/resources/schema/0.13.0/form.json
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

Move core component to 0.13.0 spec version

---

.github/workflows/spec-validate-pr.yml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
ui.tests/test-module/libs/support/index.js

Updating spec version to 0.13.0

---

jsdocs/package-lock.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/textinput.html
ui.frontend/package-lock.json
ui.frontend/src/view/FormFieldBase.js
ui.tests/test-module/package-lock.json
ui.tests/test-module/specs/checkbox/checkbox.runtime.spec.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.spec.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
ui.tests/test-module/specs/dropdown/dropdown.runtime.spec.js
ui.tests/test-module/specs/emailinput/emailinput.runtime.spec.js
ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js
ui.tests/test-module/specs/switch/switch.runtime.spec.js
ui.tests/test-module/specs/telephoneinput/telephoneinput.runtime.spec.js
ui.tests/test-module/specs/textinput/textinput.runtime.spec.js

Added condition on description and error message in aria-describedby

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/clientlibs/editor/utils/utils.js
ui.tests/test-module/specs/numberinput/numberinput.authoring.spec.js

FORMS-12822 : format should not be visible when no pattern is selected

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
examples/core/pom.xml
parent/pom.xml

re-enable RTL in 65 branch

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/clientlibs/site/js/termsandconditionsview.js
ui.tests/test-module/specs/termsandconditions/tnc.runtime.spec.js

Readonly & Disable were not working in TNC component

---

.circleci/docker-compose.yml
parent/pom.xml
ui.tests/test-module/specs/wizard/wizard.locale.spec.js

Moving to 15860 image

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFieldImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextImplTest.java
bundles/af-core/src/test/resources/form/image/exporter-image-customized.json
bundles/af-core/src/test/resources/form/image/exporter-image-datalayer.json
bundles/af-core/src/test/resources/form/image/exporter-image.json
bundles/af-core/src/test/resources/form/termsandconditions/exporter-termsandconditions.json
bundles/af-core/src/test/resources/form/text/exporter-text-customized.json
bundles/af-core/src/test/resources/form/text/exporter-text-datalayer.json
bundles/af-core/src/test/resources/form/text/exporter-text.json
bundles/af-core/src/test/resources/form/text/test-content.json
jsdocs/package-lock.json
ui.frontend/package-lock.json

Exclude from DoR is not working for text field

---

ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js

removing only in radio button test

---

.circleci/docker-compose.yml
parent/pom.xml
ui.tests/test-module/specs/wizard/wizard.locale.spec.js

Moving to 16145 aem release

---

.circleci/ci/it-tests.js
.circleci/docker-compose.yml

Moving to latest sites rotary aem image

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/page/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html

FORMS-13981 - Encode formDefinition with jsonString context

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/page/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html

Reverts adobe/aem-core-forms-components#1236

Revert "FORMS-13981 - Encode formDefinition with jsonString context"

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

FORMS-14305 Issues with AEM Forms Date Picker field behaviors.

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextImplTest.java
bundles/af-core/src/test/resources/form/termsandconditions/exporter-termsandconditions.json
bundles/af-core/src/test/resources/form/text/exporter-text-customized.json
bundles/af-core/src/test/resources/form/text/exporter-text-datalayer.json
bundles/af-core/src/test/resources/form/text/exporter-text.json
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/text/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/_cq_dialog/.content.xml
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/package-lock.json
ui.tests/test-module/specs/image/image.authoring.spec.js
ui.tests/test-module/specs/text/text.authoring.spec.js
ui.tests/test-module/specs/text/text.runtime.spec.js

FORMS-14461 Reset resets static text.

---

.gitignore
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/util/ComponentUtilsTest.java

Form fragment support in Universal Editor

---

it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
ui.tests/test-module/specs/rum/rum.runtime.spec.js

FORMS-14545 Adding custom submit test behind FT

---

ui.tests/test-module/specs/recaptcha/recaptcha.runtime.spec.js

FORMS-14580 | Retiring FT-FORMS-8771

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/page/.content.xml
it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/numberinput/validation/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/numberinput/validation/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/page/afv2/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputwidget.js
ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
ui.tests/test-module/specs/page/pagev2.runtime.spec.js
ui.tests/test-module/specs/recaptcha/recaptcha.runtime.spec.js

Sync dev to master

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractContainerImpl.java

@trivial handling error if site component is adapted to resource

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/DateConstraint.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/DatePicker.java
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/_cq_dialog/.content.xml
ui.tests/test-module/specs/datepicker/datepicker.authoring.spec.js

Fixing minimum and maximum date by setting explicit save timezone

---

ui.tests/test-module/specs/rum/rum.runtime.spec.js

Fixing RUM related test case including visitorId change

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/Utils.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-aem-allowed-components.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-aem-responsive-grid-properties.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-container-dor-properties.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-data-constraints.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-data-layer.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-defaults.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-dor-properties.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-events.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-label.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-properties.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-property-restrictions.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-sign-properties.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form-signer-properties.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/adaptive-form.schema.json
bundles/af-core/src/test/resources/schema/0.14.0/form.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
ui.tests/test-module/libs/support/index.js
ui.tests/test-module/specs/rum/rum.runtime.spec.js

Move core component to 0.14.0 spec version | RTC approved

---

it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-locale/js/languageinit.js
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/customfunctions/populate-dropdown/.content.xml
ui.tests/test-module/specs/customfunctions/dropdown.enum.enumName.spec.js

Test case to reduce enum after enum gets initialized

---

ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/formcontainer.html

FORMS-15116 Load coral library only in authoring

---

it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/recaptcha/v2checkbox/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/recaptcha/basic/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/recaptcha/enterprisescore/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/recaptcha/v2checkbox/.content.xml
it/content/src/main/content/jcr_root/content/forms/sites/core-components-it/site-with-captcha-afv2-form/.content.xml
ui.tests/test-module/specs/hcaptcha/hcaptcha.runtime.spec.js
ui.tests/test-module/specs/recaptcha/recaptcha.runtime.spec.js
ui.tests/test-module/specs/sites/captchaEmbed.runtime.spec.js

FORMS-15098 | Adding e2e test cases for captcha failure

---

ui.tests/test-module/specs/rum/rum.runtime.spec.js

Changing RUM VisitorId to sid key name change

---

ui.tests/test-module/specs/ruleeditor/ruleEditor.runtime.spec.js

FORMS-15088: skip submit error handler test-cases

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

FORMS-11775 Fixing issues related to edit pattern in date picker

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/customfunctions/populate-dropdown/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
ui.frontend/clientlib.config.cjs
ui.frontend/src/view/FormOptionFieldBase.js
ui.tests/test-module/specs/customfunctions/dropdown.enum.enumName.spec.js

 Fixing enum and enumNames during initialize

---

ui.frontend/package-lock.json
ui.frontend/package.json

updating af-core version

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/ruleeditor/submit/submitcustomerrorhandler/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/ruleeditor/submit/submitdefaulterrorhandler/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/ruleeditor/submit/submiterrorhardcodedhandler/.content.xml
ui.tests/test-module/specs/ruleeditor/ruleEditor.runtime.spec.js

FORMS-15088: fix rule editor submit error handler tests

---

ui.tests/test-module/specs/embedFormsInSiteOverrideConfig/embedFormsInSiteOverrideConfig.spec.js

FORMS-14275 Embed config override tests apply

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormStructureParserImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormStructureParserImplTest.java
bundles/af-core/src/test/resources/form/formstructparser/test-content.json

fix(eds): json encoding breaks form in eds

---

ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

Improving date picker test case as per customer use-case

---

it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/tabsontop/datepicker/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/tabsontop/datepicker/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/js/tabs.js
ui.frontend/src/view/FormTabs.js
ui.tests/test-module/specs/tabsontop/tabsontop.runtime.spec.js

FORMS-14687 Fixing initialization of tabsontop runtime 

---

ui.frontend/package-lock.json
ui.frontend/package.json

Reverts adobe/aem-core-forms-components#1304

Revert "updating af-custom-functions to 1.0.9"

---

ui.frontend/package-lock.json
ui.frontend/package.json

Screen Reader is not notifying the Success message
[FORMS-14486](https://jira.corp.adobe.com/browse/FORMS-14486) Screen Reader is not notifying the Success message

updating af-custom-functions to 1.0.9

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
ui.tests/test-module/specs/customfunctions/dropdown.enum.enumName.spec.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.thai.locale.spec.js

Fixing edge cases related to options in dropdown

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormConstants.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FileInputImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v3/form/FileInputImplV3.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FileInputImplTest.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v3/form/FileInputImplV3Test.java
bundles/af-core/src/test/resources/form/fileinput/exporter-fileinput-datalayer.json
bundles/af-core/src/test/resources/form/fileinput/exporter-fileinput.json
bundles/af-core/src/test/resources/form/fileinput/exporter-multiselect-fileinput-withNoType.json
bundles/af-core/src/test/resources/form/fileinputv2/exporter-fileinput-customized.json
bundles/af-core/src/test/resources/form/fileinputv2/exporter-multiselect-fileinput-withNoType.json
bundles/af-core/src/test/resources/form/fileinputv2/exporter-multiselect-fileinput.json
bundles/af-core/src/test/resources/form/fileinputv2/test-content.json
bundles/af-core/src/test/resources/form/fileinputv3/exporter-fileinput-customized.json
bundles/af-core/src/test/resources/form/fileinputv3/exporter-fileinput-datalayer.json
bundles/af-core/src/test/resources/form/fileinputv3/exporter-fileinput.json
bundles/af-core/src/test/resources/form/fileinputv3/exporter-multiselect-fileinput-withNoType.json
bundles/af-core/src/test/resources/form/fileinputv3/exporter-multiselect-fileinput.json
bundles/af-core/src/test/resources/form/fileinputv3/test-content.json
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/fileinput/_cq_template.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/editor/js/editDialog.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v3/fileinput/README.md
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v3/fileinput/_cq_dialog/.content.xml
ui.frontend/package-lock.json
ui.tests/test-module/package-lock.json
ui.tests/test-module/specs/fileinput/fileinput.authoring.spec.js

Remove Type from JCR & add button text in custom properties

---

.circleci/docker-compose.yml
ui.tests/test-module/specs/actions/customProperties/customProperties.spec.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.authoring.spec.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

Fixing flaky test

---

.circleci/ci/ci.js
.circleci/ci/it-tests.js

Fixing latest version script

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js

Fixing date picker issues

---

it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
it/apps/src/main/content/jcr_root/apps/forms-core-components-it/components/textinput/v1/textinput/clientlibs/site/js/textinputview.js
it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/ruleeditor/uichange/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/ruleeditor/uichange/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/clientlibs/site/js/emailinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/hcaptcha/v1/hcaptcha/clientlibs/site/js/hcaptchawidget.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/site/js/numberinputwidget.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/recaptcha/v1/recaptcha/clientlibs/site/js/recaptchaview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/recaptcha/v1/recaptcha/clientlibs/site/js/recaptchawidget.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/clientlibs/site/js/telephoneinputview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/js/textinputview.js
ui.frontend/package-lock.json
ui.frontend/package.json
ui.frontend/src/index.js
ui.frontend/src/view/FormCheckBox.js
ui.frontend/src/view/FormField.js
ui.tests/test-module/package-lock.json
ui.tests/test-module/specs/ruleeditor/uichange.runtime.spec.js

FORMS-15481 Adding ui change event to update model value

---

.circleci/config.yml

Fixing browser tools

---

ui.tests/test-module/specs/rum/rum.runtime.spec.js

Skipping rum spec

---

examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-base/.content.xml
examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/clientlibs/forms-clientlib-site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/clientlibs/editor/utils/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/datalayer/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v2/fileinput/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/recaptcha/v1/recaptcha/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/switch/v1/switch/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/clientlibs/site/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/draftsandsubmissions/v1/draftsandsubmissions/clientlibs/site/.content.xml
ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/searchlister/v1/searchlister/clientlibs/site/.content.xml

Fixing client libs compilation error

---

it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/ruleeditor/set_property_test/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/ruleeditor/set_property_test/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/fieldTemplates/longDescription.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/fieldTemplates/questionMark.html
ui.frontend/package-lock.json
ui.frontend/package.json
ui.frontend/src/view/FormFieldBase.js
ui.tests/test-module/specs/button/button.runtime.spec.js
ui.tests/test-module/specs/customization/customtextinput.runtime.repeatability.spec.js
ui.tests/test-module/specs/customization/customtextinput.runtime.spec.js
ui.tests/test-module/specs/dropdown/dropdown.runtime.spec.js
ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
ui.tests/test-module/specs/panelcontainer/panelcontainer.runtime.complex.spec.js
ui.tests/test-module/specs/prefill/customprefill.spec.js
ui.tests/test-module/specs/ruleeditor/ruleEditor.runtime.spec.js
ui.tests/test-module/specs/tabsontop/tabsontop.runtime.spec.js
ui.tests/test-module/specs/textinput/textinput.runtime.spec.js

Some Properties like 'required' 'description' and 'label' were not getting updated when set via rule 'When Form is Initialized'.
Further, the 'description' was never getting updated as if no description was authored initially then the description div was explicitly ignored in the Sightly. As a fix, included the long description div (which is always hidden by default until question mark icon is clicked), and marked the questionMark div as hidden unless we see that the description is present.

few properties were not getting updated via rules on form initialization

---

it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/actions/submit/validate/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/actions/submit/validate/.content.xml
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/specs/actions/submit/submit.runtime.spec.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
ui.tests/test-module/specs/prefill/customprefill.spec.js

Invalid field should fail the submission

---

.circleci/ci/accessibilityConfig.json
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/accessibility/.content.xml

fix: adding exception for accessibility failing in the pipeline

---

ui.tests/test-module/specs/formcontainer.spec.js

FORMS-16142 Updated test case as auto save tab name has changed

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/toolbaractionhook.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.authoring.spec.js

 RTE fix for WCM components

---

ui.frontend/src/constants.js

Updating js docs

---

ui.frontend/package-lock.json
ui.frontend/package.json

@releng updating af-core to support adding instance with data

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/site/js/accordionview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/commons/js/common.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/contentframe/js/wizard.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/js/wizardview.js

Fixing wizard mixin

---

it/apps/src/main/content/jcr_root/apps/forms-core-components-it/components/container/v1/container/container.html

Adding firefox reset sample

---

ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js

Fixing initialize in dispatch

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/de.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/en.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/es.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/fr.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/it.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/ja.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/ko-kr.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/pt-br.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/zh-cn.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/zh-tw.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
ui.tests/test-module/specs/autosave/autosave.runtime.spec.js

FORMS-15478 Added localize success and error message for draft

---

ui.tests/test-module/specs/button/button.authoring.cy.js
ui.tests/test-module/specs/datepicker/datepicker.authoring.cy.js

Flaky test fix

---

.circleci/ci/it-tests.js
.circleci/config.yml
.circleci/docker-compose.yml

@releng latest aem image

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html

…packages to support this encoding

fix: removed json encoding as 6.5 needs huge version bump in sightly packages to support this encoding

---

ui.tests/test-module/specs/ruleeditor/ruleEditor.authoring.cy.js

FORMS-15321: added delay in rule editor authoring tests

---

it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/ruleeditorhook.js
ui.tests/test-module/specs/ruleeditor/ruleEditor.authoring.cy.js

FORMS-14068: Enable rule-editor spa in core-components

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/_cq_dialog/.content.xml
ui.tests/test-module/specs/fileinput/fileinput.authoring.cy.js

Fixing default value of type in file input

---

ui.frontend/src/view/FormContainer.js
ui.tests/test-module/specs/formcontainer.cy.js

FORMS-16930 Allow press of enter on dropdown and submit

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/checkbox.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/clientlibs/site/js/checkboxview.js
ui.tests/test-module/specs/checkbox/checkbox.authoring.cy.js
ui.tests/test-module/specs/checkbox/checkbox.runtime.cy.js

Read-only support in checkbox component

---

.github/workflows/sync-pr.yml

Fixing vulnerability in GH action

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/switch/v1/switch/clientlibs/editor/js/editDialog.js

Translation support for strings in switch

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/fileinput/fileinputv3/basic/.content.xml
ui.frontend/src/view/FormFileInputWidgetBase.js
ui.tests/test-module/specs/fileinput/fileinputv3.runtime.cy.js

Configured custom validation messages in file attachment

---

.github/workflows/exporter-validate-pr.yml

Fixing gh workflow

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/_cq_dialog/.content.xml

Move areOptionsRichText above Options

---

.circleci/docker-compose.yml

@releng moving to latest rotary image

---

it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
ui.tests/test-module/specs/fileinput/fileinputstring.runtime.cy.js

Adding FT for type string in file attachment

---

ui.frontend/src/view/FormFileInputWidgetBase.js

Adding more image extension/mimetype map list

---

it/core/pom.xml
it/core/src/main/java/com/adobe/cq/forms/core/components/it/service/HeadlessTransportHandler.java
it/core/src/main/java/com/adobe/cq/forms/core/components/it/service/OAuth2Client.java

Using Oauth2 via certificate based authentication and JWT

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/checkboxgroup/basic/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/radiobutton/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.cy.js
ui.tests/test-module/specs/radiobutton/radiobutton.runtime.cy.js

FORMS-17206 Reset check box group marks checkbox group field invalidates even if not required

---

.gitignore

Adding npm debug log in gitignore

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2WithAutoSave.json
bundles/af-core/src/test/resources/form/formcontainer/test-content-auto-save.json
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
ui.frontend/package-lock.json
ui.frontend/package.json

[FORMS-16370] [FORMS-16201] Re-saving of draft creates new draft instead of updating existing draft

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/termsandconditions.html

Fixing terms and condition initial state.

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImplTest.java
bundles/af-core/src/test/resources/form/image/exporter-image-customized.json
bundles/af-core/src/test/resources/form/image/test-content.json
it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/image/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/clientlibs/site/js/imageview.js
ui.tests/test-module/specs/image/image.authoring.cy.js
ui.tests/test-module/specs/image/image.runtime.cy.js

Add DataRef in Image Component

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImplTest.java
bundles/af-core/src/test/resources/form/image/exporter-image-customized.json
bundles/af-core/src/test/resources/form/image/test-content.json
it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/image/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/clientlibs/site/js/imageview.js
ui.tests/test-module/specs/image/image.authoring.cy.js
ui.tests/test-module/specs/image/image.runtime.cy.js

Dev master27 jan

---

ui.frontend/src/GuideBridge.js

Fixing cross origin issues

---

.circleci/config.yml

Disabling old core component build since core component is part of cloud

---

.circleci/config.yml

Fixing readme.md script

---

ui.frontend/package-lock.json
ui.frontend/package.json

@releng updating af-custom-function to 1.0.14

---

bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/aemform/AEMFormImpl.java
bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/aemform/AEMFormImplTest.java
bundles/core/src/test/resources/aemform/test-content.json

Fixing sling output mappings in aemform embed component

---

ui.frontend/package-lock.json
ui.frontend/package.json

@releng updating af-core

---

it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/actions/submit/validate/.content.xml
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/specs/title/title.authoring.cy.js

Updating test collateral for reference

---

bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form.schema.json
ui.tests/test-module/specs/checkboxgroup/checkboxgroup.authoring.cy.js

Updating schema

---

all/pom.xml
bundles/af-core/pom.xml
bundles/core/pom.xml
examples/all/pom.xml
examples/core/pom.xml
examples/pom.xml
examples/ui.apps/pom.xml
examples/ui.content/pom.xml
it/apps/pom.xml
it/config/pom.xml
it/content/pom.xml
it/core/pom.xml
jsdocs/pom.xml
parent/pom.xml
pom.xml
ui.af.apps/pom.xml
ui.apps/pom.xml
ui.frontend/pom.xml
ui.tests/pom.xml
ui.tests/test-module/specs/datepicker/datepicker.authoring.cy.js

updating dev snapshot version

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/CacheManager.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/util/ComponentUtilsTest.java

feat: adding caching of supported submit action api response

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/CacheManager.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/util/ComponentUtilsTest.java
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/specs/datepicker/datepicker.authoring.cy.js

Dev master12 mar

---

ui.af.apps/pom.xml

Fixing OOTB components

---

ui.af.apps/pom.xml

Adding missing components in /libs.

---

.circleci/docker-compose.yml

update aem base image

---

it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
ui.frontend/src/RuleUtils.js
ui.frontend/src/utils.js

FORMS-17107: Client-side custom function parsing changes

---

it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/ruleeditor/basic/.content.xml
ui.tests/test-module/specs/ruleeditor/runtime/ruleEditorSanity.runtime.cy.js

FT_FORMS-17107: disable client-side custom function parsing toggle

---

.circleci/config.yml

Lighthouse version 12.5.0 to be used in circleci pipelines

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/widget.html

FORMS-18706: Group of checkboxes not associated with group label @sunnym @vavarshn

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/css/datepickerwidget.css

FORMS-18622: Desktop, RWD Tablet, RWD Mobile - Text content lacks 4.5:1 contrast ratio @sunnym @vavarshn

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/radiobutton.html

FORMS-18645: Desktop, RWD Tablet, RWD Mobile - Group of radio buttons not associated with group label @sunnym @vavarshn

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

FORMS-2896: Adding excludeFromDoRIfHidden in formModel json

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/textinput/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/js/textinputview.js
ui.tests/test-module/specs/aemEmbedContainer/aemEmbedContainer.runtime.cy.js
ui.tests/test-module/specs/embedFormsInSite/embedFormsInSite.runtime.cy.js
ui.tests/test-module/specs/textinput/textinput.runtime.cy.js

Fixing text area to accept new line character (enter).

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

Forms-2896: addition new excludeFromDoRIfHidden property in form container model

---

it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/prefill/basic/.content.xml
ui.frontend/src/view/FormFileInputWidgetBase.js
ui.tests/test-module/specs/fileinput/fileinputv3.runtime.cy.js
ui.tests/test-module/specs/prefill/customprefill.cy.js

Fix size issue on uploading the file again

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/scribble/v1/scribble/clientlibs/editor/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/scribble/v1/scribble/clientlibs/editor/js.txt
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/scribble/v1/scribble/clientlibs/editor/js/editDialog.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/scribble/v1/scribble/clientlibs/site/.content.xml

Correction in scribble component

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/js/textinputview.js
ui.tests/test-module/specs/textinput/textinput.runtime.cy.js

Fixing positional enter in text area.

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/scribble/v1/scribble/clientlibs/site/js/scribbleview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/scribble/v1/scribble/scribble.html

Accessibility fix

---

ui.frontend/package.json
ui.frontend/src/customFunctions.js

FORMS-20002: Added exportFormData in OOTB functions

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/_cq_dialog/.content.xml

Remove duplicate attribute & enabled manual entry of autofill attributes

---

.circleci/config.yml

Fixing circle ci configuration

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractContainerImpl.java

@trivial Resolving localization issue with the text component when used with Open API

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/accordion.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/panelcontainer/v1/panelcontainer/responsiveGrid.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/wizard.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v2/wizard/wizard.html

FORMS-18739: Visual heading text is not marked as heading

---

ui.frontend/src/view/FormTabs.js

https://jira.corp.adobe.com/browse/FORMS-18801

FORMS-18801: State of active component lacks 3 to 1 contrast ratio @sunnym @vavarshn

---

ui.frontend/package.json

FORMS-20749: Update af-core version to 0.22.143

---

.circleci/config.yml

Fixing adobe bot github token environment variable

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/verticaltabs.html

FORMS-18718: Desktop, RWD Tablet, RWD Mobile - Visual heading text is not marked as heading @sunnym @vavarshn

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
ui.frontend/package.json

codePA:  Update af-core version , update fd:excludeFromDoRIfHidden

---

ui.frontend/src/view/FormContainer.js
ui.tests/test-module/specs/formcontainer.cy.js

Fixing enter keydown event on forms

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.cy.js

 FORMS-21023: Close Date-Picker on touch-event in mobile/tablet devices

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
ui.tests/test-module/specs/datepicker/datepicker.runtime.cy.js

DevToMaster 22-07

---

bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java

Dev to master2507

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/button.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/checkbox.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/widget.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v4/fileinput/fileinput.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/radiobutton.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/switch/v1/switch/switch.html
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/js/wizardview.js
ui.frontend/src/view/FormFieldBase.js

DevToMaster 28 August 2025

---

ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/commons/js/common.js
ui.tests/test-module/specs/accordion/accordion.runtime.cy.js

Fixing Accordion panel cannot collapse when a Text component is the first item.

---

.circleci/ci/it-tests.js
.circleci/docker-compose.yml
bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/servlets/FormMetaDataDataSourceServlet.java
examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml
examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/templates/af-blank-v2/policies/.content.xml
examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/templates/af-xfa-blank-v2/policies/.content.xml
it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/policies/.content.xml
it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/textinput/basic/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/clientlibs/editor/utils/utils.js
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/_cq_design_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/_cq_design_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/README.md
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/_cq_design_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/_cq_dialog/.content.xml
ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/editor/js/editDialog.js
ui.frontend/package-lock.json
ui.frontend/package.json
ui.tests/test-module/specs/aemEmbedContainer/aemEmbedContainer.runtime.cy.js
ui.tests/test-module/specs/embedFormsInSite/embedFormsInSite.runtime.cy.js
ui.tests/test-module/specs/numberinput/numberinput.runtime.cy.js
ui.tests/test-module/specs/page/pagev2.runtime.cy.js
ui.tests/test-module/specs/ruleeditor/authoring/navigatePanel.authoring.cy.js
ui.tests/test-module/specs/ruleeditor/authoring/ruleEditor.authoring.cy.js
ui.tests/test-module/specs/telephoneinput/telephoneinput.authoring.cy.js
ui.tests/test-module/specs/textinput/textinput.authoring.cy.js
ui.tests/test-module/specs/textinput/textinput.runtime.cy.js

FORMS-19439 adding support for display format in text input

---

jsdocs/jsdoc.conf.json
ui.frontend/src/view/FormCheckBox.js
ui.frontend/src/view/FormFileInput.js
ui.frontend/src/view/FormOptionFieldBase.js

Fixing js doc
