adobe/aem-core-forms-components

- bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/formsportal/LinkImpl.java
- bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/formsportal/Link.java
- bundles/core/src/main/java/com/adobe/cq/forms/core/components/models/formsportal/package-info.java
- bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/formsportal/link/LinkImplTest.java
- bundles/core/src/test/resources/link/exporter-linkcomponent-v1.json
- examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/forms-and-communications-portal/link/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v1/link/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/fd/components/formsportal/link/v1/link/link.html
Also unhide Asset Type in authoring and make
default asset type as NONE
formsportal model package version bumped as required
by versioning plugin
@review @rismehta @vdua
> CQ-4301939 Rename url inside Link Component

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/base/v1/base/_cq_dialog/.content.xml
Changing the dorColspan resourceSuperType to Numeric Field input.
Reason:
1. Autocomplete Granite UI component is deprecated and had styling issues which reduced the ease of use of dropdown in the coral panel as it did not fit in property to let the user see the available options from the dropdown. 
2. The field should allow only number input but, using autocomplete the user could earlier enter non-numeric values. 
[CQ-4348552](https://jira.corp.adobe.com/browse/CQ-4348552)
> [CQ-4348552] DoR dropdown styling issue

- ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/aemform.html
- ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/formfooterlibs.html
- ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/formheaderlibs.html
- ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/iframe.html
Tested in local by creating a form and embedding in site.
The wizard component js and css files are needed in authoring mode as well.
css is loaded in head and js is loaded at the bottom of the bpdy.
> [CQ-4350599] added footerlibs and headerLibs in aem container v2 for sites, this will enable to load core components runtime library in iframe mode

- ui.tests/test-module/specs/accordion/accordion.authoring.spec.js
- ui.tests/test-module/specs/aemformcontainer.spec.js
- ui.tests/test-module/specs/portal/draftsnsubmissionscomponent.spec.js
- ui.tests/test-module/specs/wizard/wizard.authoring.spec.js
- race condition in editor code is causing this
- more details at, https://www.cypress.io/blog/2020/12/03/retry-rerun-repeat/ a Please enter the commit message for your changes. Lines starting
> @trivial Adding retry mechanism for flaky test

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/js/tabs.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/clientlibs/site/js/verticaltabs.js
- ui.tests/test-module/specs/datepicker/datepicker.authoring.spec.js
- ui.tests/test-module/specs/numberinput/numberinput.authoring.spec.js
- ui.tests/test-module/specs/tabsontop/tabsontop.authoring.spec.js
- ui.tests/test-module/specs/wizard/wizard.authoring.spec.js
Added test case to check this behaviour :-
The issue was because the editor hook sends a navigation event as soon as the element is added to tab before the tab's constructor call . hence the _self._elements cache doesn't have the newly added elements and while checking the array at the index , the call fails and constructor call doesn't happens.
When we refresh the constructor call happens resulting in correct cache formation and hence correct navigation.
> [FORMS-7828] resolved problem of navigation not working in authoring without refresh in case of horizontal and vertical tabs

- .circleci/config.yml
- README.md
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextInputImplTest.java
- bundles/af-core/src/test/resources/form/textinput/exporter-textinput-blank-dataref.json
- bundles/af-core/src/test/resources/form/textinput/test-content.json
- it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/.content.xml
- it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/css.txt
- it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js.txt
- it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
- it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/af2-custom-function/.content.xml
- it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/af2-custom-function/basic/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/af2-custom-function/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/af2-custom-function/basic/.content.xml
- parent/pom.xml
- ui.frontend/package.json
- ui.frontend/src/HTTPAPILayer.js
- ui.frontend/src/customFunctions.js
- ui.frontend/src/index.js
- ui.frontend/src/utils.js
- ui.tests/test-module/specs/customFunctionTest.spec.js
> Dev2master 03 jul23

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/js/wizardview.js
This fix was needed to allow navigation inside wizard in comparing two forms
https://jira.corp.adobe.com/browse/FORMS-10513
> Allowing Wizard to navigate if children exist but their view isn't initialised

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/footer/v1/footer/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/recaptcha/v1/recaptcha/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/telephoneinput/v1/telephoneinput/_cq_htmlTag/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/_cq_htmlTag/.content.xml
- ui.tests/test-module/specs/checkbox/checkbox.runtime.spec.js
- ui.tests/test-module/specs/checkboxgroup/checkboxgroup.authoring.spec.js
- ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.spec.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
- ui.tests/test-module/specs/dropdown/dropdown.runtime.spec.js
- ui.tests/test-module/specs/emailinput/emailinput.runtime.spec.js
- ui.tests/test-module/specs/fileinput/fileinput.runtime.spec.js
- ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
- ui.tests/test-module/specs/radiobutton/radiobutton.authoring.spec.js
- ui.tests/test-module/specs/radiobutton/radiobutton.runtime.spec.js
- ui.tests/test-module/specs/recaptcha/recaptcha.runtime.spec.js
- ui.tests/test-module/specs/telephoneinput/telephoneinput.runtime.spec.js
- ui.tests/test-module/specs/textinput/textinput.runtime.spec.js
All input components (excluding date, email and telephone fields) have the same classes for parent and child containers.
FORMS-10478
> Parent element have same classes for some components

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
- ui.tests/test-module/libs/support/commands.js
As discussed with Rishi, the sibling div should have the selector as the ID of form and selecting the div with the same and adding the loading class on it later removing as well with the same steps.
However the test cases were already written in command.js file therefore, I have made the corrections in the same for the updated logic.
the new updates has been added to the readme file as well.
FORMS-9362: Loading Icon Behind Fields
> FORMS-9362: loading icon behind fields

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/_cq_editConfig.xml
- ui.tests/test-module/specs/button/button.authoring.spec.js
the editElementQuery was label initially but in button it should be span as we have used span for the title in place of label 
added the necessary test cases for the particular change.
FORMS-3342 Title issue is while inline editing the title for Button, Reset and Submit button.
> Forms-3342 editElementQuery changes as span

- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/SwitchImplTest.java
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/switch/v1/switch/_cq_dialog/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/switch/v1/switch/clientlibs/editor/css/switcheditor.css
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/switch/v1/switch/clientlibs/editor/js/editDialog.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/switch/v1/switch/switch.html
- ui.tests/test-module/specs/switch/switch.authoring.spec.js
> fixed switch rich text issue

- examples/ui.content/src/main/content/META-INF/vault/filter.xml
- examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/policies/.content.xml
- ui.tests/test-module/libs/support/commands.js
- ui.tests/test-module/specs/switch/switch.authoring.spec.js
> updated styles for sites editor to hide/unhide switch labels

- it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/setfocus/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/setfocus/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/clientlibs/site/js/textview.js
- ui.tests/test-module/specs/setFocusTests.runtime.spec.js
adding a scroll in view function for text only as text doesn't have any field to apply setActive.
respected test case is also added in the same.
FORMS-11276: Text component does not appear in the viewport when the 'setFocus' is triggered on the Text Component.
> FORMS-11276: Text component does not appear in the viewport when the 'setFocus' is triggered on the Text Component.

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/datepicker.html
- ui.tests/test-module/libs/support/commands.js
- ui.tests/test-module/specs/datepicker/datepicker.authoring.spec.js
> fixed default value for date not showing in authoring

- it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/document-of-record/.content.xml
- it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/document-of-record/dor-form/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/document-of-record/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/document-of-record/dor-form/.content.xml
- ui.tests/test-module/libs/support/commands.js
- ui.tests/test-module/specs/documentOfRecordTest.spec.js
> Added Test Case for Document of Record generation

- ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/aemform.html
- ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/aemform.html
- ui.tests/test-module/specs/aemEmbedContainer/aemEmbedContainer.runtime.spec.js
Improvised the code readability by replacing the dataRef and wcmmode as different parameters. 
I have checked both cases 
1. if only wcmmode is passed 
2. if both are passed 
it is because the wcmmode will always be disabled for iframe. 
FORMS-11570: Abbvie 2023 AEM Forms - dataRef
> FORMS-11259:  Avoid dataRef parameter in Iframe when no value available

- ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v1/aemform/formcontainer.html
- ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/formcontainer.html
JIRA for the test Cases: https://jira.corp.adobe.com/browse/FORMS-13508
> FORMS-13392 Role main check

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.layout.spec.js
> Fixes datepicker layout issues

- it/apps/src/main/content/jcr_root/apps/forms-core-components-it/components/textinput/v1/textinput/clientlibs/site/js/textinputview.js
- jsdocs/package-lock.json
- ui.frontend/package-lock.json
- ui.frontend/package.json
- ui.frontend/src/view/FormContainer.js
- ui.tests/test-module/package-lock.json
- ui.tests/test-module/specs/customization/customtextinput.runtime.spec.js
> Invalid event customization

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/footer/v1/footer/footer.html
Footer resizes on editing content. It was happening because RTE inline editor changes the parent div class "cq-Editable-dom" to "section text cq-Editable-dom" and remove all other classes. We are adding another div element to keep the css and wrapping child components in separate div.
> CQ-4348557 adding another div to stop footer getting resized

- examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/radiobutton/_cq_template.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/componentutils.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/replacehook.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/_cq_template.xml
- ui.tests/test-module/specs/replaceaction/replacelayout-container.authoring.spec.js
> FORMS-12667 Update type property on replacing checkboxgroup to radio group

- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/prefill/basic/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
- ui.tests/test-module/specs/prefill/customprefill.spec.js
> FORMS-13760 Date picker display value not working during prefill

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
> datepicker timezone issue on view layer fixed

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/servlets/FormMetaDataDataSourceServlet.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/Base.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/servlets/FormMetaDataDataSourceServletTest.java
- bundles/af-core/src/test/resources/form/datepicker/exporter-datepicker-customized.json
- bundles/af-core/src/test/resources/form/datepicker/test-content.json
- bundles/af-core/src/test/resources/form/formcontainer/datasource/test-content.json
- examples/ui.content/src/main/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml
- it/content/src/main/content/jcr_root/conf/core-components-it/settings/wcm/policies/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/numberinput/basic/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/_cq_dialog/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/editor/js/editDialog.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/_cq_dialog/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/editor/js/editDialog.js
- ui.frontend/src/view/FormContainer.js
- ui.frontend/src/view/FormFileInputWidget.js
- ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
> FORMS-13851 Support for language in date picker and number input

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/dropdown.html
Description & Screenshots of the change are present in the jira comment
https://jira.corp.adobe.com/browse/FORMS-14013
> FORMS-14013 - Fixing Dropdown that had a selected value without default/placeholder set

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/dropdown.html
- ui.tests/test-module/specs/dropdown/dropdown.runtime.spec.js
> FORMS-14013 - Testcase added - Fixing Dropdown that had a selected value without default/placeholder set

- ui.frontend/src/view/FormFileInputWidget.js
- ui.tests/test-module/specs/fileinput/fileinput.runtime.spec.js
> Forms 11746 allow attaching same file

- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/fileinput/basic/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v2/fileinput/clientlibs/site/js/fileinputview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
- ui.frontend/src/view/FormFieldBase.js
- ui.tests/test-module/specs/fileinput/fileinput.runtime.spec.js
> Read-only is not working in file-attachment

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractOptionsFieldImpl.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DropDownImplTest.java
- bundles/af-core/src/test/resources/form/dropdown/test-content.json
Currently, when not providing enumNames in the dialog, the values from enums are copied to it in js before being submitted to jcr. An assumption of the constant presence of enumNames was made in the sling model code. But we have a use case in UE where enums can be provided without enumNames, which breaks this, hence the fix.
> FORMS-14018 - Fix for dropdown not working when enumNames are not provided

- .circleci/docker-compose.yml
- parent/pom.xml
- ui.tests/test-module/specs/wizard/wizard.locale.spec.js
Revert "Moving to 15860 image (#1212)"
This reverts commit c2270016979584dfdb635a25b1995b8e91eac3c8.
> CM build is failing as 2.24.4 version is not available

- .circleci/docker-compose.yml
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FragmentImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/Fragment.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FragmentImplTest.java
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/fragment/test-fragment/.content.xml
- parent/pom.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragment/v1/fragment/fragment.html
- ui.tests/test-module/specs/aemEmbedContainer/aemEmbedContainer.runtime.spec.js
- ui.tests/test-module/specs/fragment/fragment.runtime.spec.js
- ui.tests/test-module/specs/wizard/wizard.locale.spec.js
> Devtomaster 10 may2024

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractBaseImpl.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextInputImplTest.java
- bundles/af-core/src/test/resources/form/textinput/exporter-textinput-with-viewtype.json
- bundles/af-core/src/test/resources/form/textinput/test-content.json
This is a UE usecase, to override `:type` of the json by providing `fd:viewType` property in the jcr node of any component.
> UE: Supporting custom viewType in sling models

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
- ui.tests/test-module/specs/page/pagev2.runtime.spec.js
When migrating from eds to master. 
- We moved the getFormDefinition Api from formContainer to FormStructParser. In doing so , we adapted the resource to FormContainer object and then generated the json.
- Before since the context was with request object the currentPage variable was initiated from request obj but now this was null resulting in wrong id getting generated in eds json.
cc:- @nit23uec , @jalagari , @rismehta
> made changes in getId method where currentPage is null in case of resource adaptation

- .circleci/settings.xml
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormStructureParserImpl.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/FormStructureParserImplTest.java
- bundles/af-core/src/test/resources/form/formstructparser/test-content.json
- it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/tabsontop/datepicker/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/tabsontop/datepicker/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/js/tabs.js
- ui.frontend/src/view/FormTabs.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
- ui.tests/test-module/specs/embedFormsInSiteOverrideConfig/embedFormsInSiteOverrideConfig.spec.js
- ui.tests/test-module/specs/tabsontop/tabsontop.runtime.spec.js
> Dev to master 8th july 2024

- ui.frontend/package-lock.json
- ui.frontend/package.json
Updating the af-custom-functions to 1.0.9 
[FORMS-14041:](https://jira.corp.adobe.com/browse/FORMS-14486) Screen Reader is not notifying upon submission of a Form
> updating af-custom-functions to 1.0.9

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/checkbox.html
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/README.md
> Fixing incorrect id issue with checkbox

- ui.apps/pom.xml
> FORMS-15466 Fixing conflicting vault filter

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DatePickerImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DatePickerImplTest.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/NumberInputImplTest.java
- bundles/af-core/src/test/resources/form/datepicker/exporter-datepicker-backwardcompatible.json
- bundles/af-core/src/test/resources/form/datepicker/test-content.json
- bundles/af-core/src/test/resources/form/numberinput/exporter-numberinput-backwardcompatible-2.json
- bundles/af-core/src/test/resources/form/numberinput/test-content.json
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datepicker/basic/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/numberinput/basic/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/_cq_dialog/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/_cq_dialog/.content.xml
- ui.frontend/package-lock.json
- ui.frontend/package.json
- ui.tests/test-module/package-lock.json
- ui.tests/test-module/specs/aemEmbedContainer/aemEmbedContainer.runtime.spec.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
- ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
> Fixing exclusive maximum and minimum issue

- examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/termsandconditions/_cq_template/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/_cq_template.xml
- ui.tests/test-module/specs/termsandconditions/tnc.runtime.spec.js
> Approval checkbox required by default

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
- it/core/src/main/java/com/adobe/cq/forms/core/components/it/service/CustomAFSubmitService.java
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
- ui.frontend/src/HTTPAPILayer.js
- ui.frontend/src/utils.js
> Adding support to handle sites page language in form container (#976)

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/button.html
- ui.tests/test-module/specs/button/button.runtime.spec.js
- ui.tests/test-module/specs/customization/customtextinput.runtime.spec.js
- ui.tests/test-module/specs/textinput/textinput.runtime.spec.js
Fixed the enabled and visible attributes to reflect correctly in forms for button core component.
JIRA : https://jira.corp.adobe.com/browse/FORMS-15167
Without this change, the button component in forms was not correctly populating true and false values to 'data-cmp-enabled' and 'data-cmp-visible' attributes.
Tested the changes using cypress.
> Fixing enabled and visible attributes of Button CC

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormConstants.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/TitleImplV2.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormTitle.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/TitleImplV2Test.java
- bundles/af-core/src/test/resources/form/titleV2/exporter-title-noprops.json
- bundles/af-core/src/test/resources/form/titleV2/exporter-title-type.json
- bundles/af-core/src/test/resources/form/titleV2/exporter-title-wrongtype.json
- bundles/af-core/src/test/resources/form/titleV2/exporter-title.json
- bundles/af-core/src/test/resources/form/titleV2/test-content.json
- examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/title/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/af2-form-translation/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/title/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/title/basic/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v1/title/_cq_design_dialog/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v2/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v2/title/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v2/title/README.md
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v2/title/_cq_dialog/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v2/title/_cq_template.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v2/title/title.html
- ui.frontend/package-lock.json
- ui.tests/test-module/libs/commons/formsConstants.js
- ui.tests/test-module/package-lock.json
- ui.tests/test-module/specs/title/titleV2.authoring.spec.js
- ui.tests/test-module/specs/title/titlev2.runtime.spec.js
> V2 version of Title

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/README.md
> update number input component readme

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/AutoSaveConfigurationImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/AutoSaveConfiguration.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/AutoSaveConfigurationTest.java
- bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
- bundles/af-core/src/test/resources/form/formcontainer/test-content-auto-save.json
- it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json
- it/content/src/main/content/META-INF/vault/filter.xml
- it/content/src/main/content/jcr_root/conf/global/settings/forms/.content.xml
- it/content/src/main/content/jcr_root/conf/global/settings/forms/usc/.content.xml
- it/content/src/main/content/jcr_root/conf/global/settings/forms/usc/portal/.content.xml
- it/content/src/main/content/jcr_root/conf/global/settings/forms/usc/portal/portal/.content.xml
- it/content/src/main/content/jcr_root/content/dam/formsanddocuments/core-components-it/samples/autosave/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/autosave/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/clientlibs/editor/js/editDialog.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragmentcontainer/v1/fragmentcontainer/_cq_dialog/.content.xml
- ui.frontend/src/index.js
- ui.tests/test-module/specs/autosave/autosave.runtime.spec.js
- ui.tests/test-module/specs/formcontainer.spec.js
> Forms-14212 Implemented time based auto save

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/NumberInputImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/NumberConstraintV2.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/NumberInput.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFieldImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/NumberInputImplTest.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/util/ComponentUtilsTest.java
- bundles/af-core/src/test/resources/form/numberinput/exporter-numberinput.json
- bundles/af-core/src/test/resources/form/numberinput/test-content.json
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/numberinput/basic/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/clientlibs/editor/js/editDialog.js
- ui.tests/test-module/package-lock.json
- ui.tests/test-module/specs/numberinput/numberinput.authoring.spec.js
- ui.tests/test-module/specs/numberinput/numberinput.runtime.spec.js
- randomly chosen step as 0.01 for decimal, but it can be author defined
> Fixing Min/Max dialog fields for number input, when the type is decimal

- ui.frontend/src/view/FormContainer.js
- ui.tests/test-module/specs/formcontainer.spec.js
Pressing enter on core components redirects to thankyou page which is not the correct behaviour. This fix prevents the default behaviour of enter press on form level.
https://jira.corp.adobe.com/browse/FORMS-15630
Tested on localhost deployment and test cases tested using cypress.
> Fix default behaviour of enter press leading to form submission in core components.

- ui.frontend/package-lock.json
- ui.frontend/package.json
- ui.tests/test-module/specs/fragment/fragment.runtime.spec.js
> @releng updating af-core and af-custom-functions

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/commons/js/common.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/contentframe/js/accordion.js
> Making accordion mixin async via event handler

- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/fragment/basic/.content.xml
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/fragment/test-fragment/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/clientlibs/site/js/textview.js
- ui.frontend/package-lock.json
- ui.frontend/package.json
- ui.tests/test-module/specs/aemEmbedContainer/aemEmbedContainer.runtime.spec.js
- ui.tests/test-module/specs/fragment/fragment.runtime.spec.js
> FORMS-16296 Adding fragment test and fixing rules issue inside fragment

- it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/panelcontainer/repeatability-tests/repeatedpanelcount/.content.xml
- ui.tests/test-module/specs/repeatable/repeatable.updatelabel.cy.js
> Adding remove instance with label test

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkboxgroup/v1/checkboxgroup/clientlibs/site/js/checkboxgroupview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/dropdown/v1/dropdown/clientlibs/site/js/dropdownview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/clientlibs/site/js/fileinputview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v2/fileinput/clientlibs/site/js/fileinputview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v3/fileinput/clientlibs/site/js/fileinputview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/radiobutton/v1/radiobutton/clientlibs/site/js/radiobuttonview.js
- ui.frontend/src/view/FormFieldBase.js
- ui.tests/test-module/specs/button/button.runtime.cy.js
- ui.tests/test-module/specs/checkbox/checkbox.runtime.cy.js
- ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.cy.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.cy.js
- ui.tests/test-module/specs/dropdown/dropdown.runtime.cy.js
- ui.tests/test-module/specs/emailinput/emailinput.runtime.cy.js
- ui.tests/test-module/specs/fileinput/fileinputv3.runtime.cy.js
- ui.tests/test-module/specs/numberinput/numberinput.runtime.cy.js
- ui.tests/test-module/specs/radiobutton/radiobutton.runtime.cy.js
- ui.tests/test-module/specs/switch/switch.runtime.cy.js
- ui.tests/test-module/specs/telephoneinput/telephoneinput.runtime.cy.js
- ui.tests/test-module/specs/textinput/textinput.runtime.cy.js
> Remove aria-disabled attribute

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FieldType.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/Utils.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
- bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-aem-allowed-components.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-aem-responsive-grid-properties.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-container-dor-properties.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-data-constraints.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-data-layer.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-defaults.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-dor-properties.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-events.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-label.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-properties.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-property-restrictions.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-sign-properties.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form-signer-properties.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/adaptive-form.schema.json
- bundles/af-core/src/test/resources/schema/0.14.2/form.json
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
More standard HTML input types being added to the list of exclusive fieldTypes.
Still defaults to text-input when unrecognised.
> Adding more HTML input types to FieldType

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerwidget.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.cy.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.persian.locale.cy.js
- ui.tests/test-module/specs/datepicker/datepicker.runtime.thai.locale.cy.js
> Issue/forms 16264: Unique instantiation of calendar element of every date time picker widget 

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/_cq_dialog/.content.xml
autocomplete is deprecated by granite
> FORMS-15484: fix translataion issue with email autocomplete config options

- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextImpl.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TextImplTest.java
- bundles/af-core/src/test/resources/form/termsandconditions/exporter-termsandconditions.json
- bundles/af-core/src/test/resources/form/text/exporter-text-customized.json
- bundles/af-core/src/test/resources/form/text/exporter-text-datalayer.json
- bundles/af-core/src/test/resources/form/text/exporter-text.json
- it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/text/basic/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/_cq_dialog/.content.xml
- ui.tests/test-module/specs/text/text.authoring.cy.js
- ui.tests/test-module/specs/text/text.runtime.cy.js
> FORMS-16911 Prefill of static text with explicit data bindings

- ui.frontend/src/view/FormFileInputWidgetBase.js
- ui.tests/test-module/libs/fixtures/sample.svg
- ui.tests/test-module/libs/support/commands.js
- ui.tests/test-module/specs/fileinput/fileinputv2.runtime.cy.js
> FORMS-15852 xss security fix for svg upload in file attachment

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/commons/js/common.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/clientlibs/site/js/accordionview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/README.md
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/tabsontop/v1/tabsontop/clientlibs/site/js/tabs.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/README.md
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/verticaltabs/v1/verticaltabs/clientlibs/site/js/verticaltabs.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/README.md
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/commons/js/common.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/wizard/v1/wizard/clientlibs/site/js/wizardview.js
- ui.frontend/src/view/FormTabs.js
- ui.tests/test-module/specs/accordion/accordion.repeatability.runtime.cy.js
- ui.tests/test-module/specs/tabsontop/tabsontop.runtime.cy.js
- ui.tests/test-module/specs/tabsontop/tabsontop.runtime.repeatability.cy.js
- ui.tests/test-module/specs/verticaltabs/verticaltabs.runtime.cy.js
- ui.tests/test-module/specs/verticaltabs/verticaltabs.runtime.repeatability.cy.js
- ui.tests/test-module/specs/wizard/wizard.runtime.cy.js
- ui.tests/test-module/specs/wizard/wizard.runtime.repeatability.cy.js
> Add stepped class in wizard/tabs

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragment/v1/fragment/fragment.html
* Adding support to cache fragment initial HTML state.
* Adding support to cache fragment initial HTML state.
> Adding support to cache fragment initial HTML state. (#1507)

- ui.tests/test-module/specs/customfunctions/checkbox.enum.enumName.cy.js
- ui.tests/test-module/specs/customfunctions/dropdown.enum.enumName.cy.js
- ui.tests/test-module/specs/customfunctions/radiobutton.enum.enumName.cy.js
- ui.tests/test-module/specs/ruleeditor/authoring/ruleEditor.authoring.cy.js
- ui.tests/test-module/specs/ruleeditor/runtime/customFunction.runtime.cy.js
- ui.tests/test-module/specs/ruleeditor/runtime/ruleEditorSanity.runtime.cy.js
- ui.tests/test-module/specs/ruleeditor/runtime/uichange.runtime.cy.js
> FORMS-17559: fix rule-editor test

- .gitignore
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/ReservedProperties.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormContainer.java
- bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/package-info.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/StaticImageImplTest.java
- bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImplTest.java
- bundles/af-core/src/test/resources/form/formcontainer/exporter-formcontainerv2WithAutoSave.json
- bundles/af-core/src/test/resources/form/formcontainer/test-content-auto-save.json
- bundles/af-core/src/test/resources/form/image/exporter-image-customized.json
- bundles/af-core/src/test/resources/form/image/test-content.json
- it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-custom-function/js/functions.js
- it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/image/basic/.content.xml
- parent/pom.xml
- pom.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fragment/v1/fragment/fragment.html
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/_cq_dialog/.content.xml
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/image/v1/image/clientlibs/site/js/imageview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/termsandconditions.html
- ui.frontend/package-lock.json
- ui.frontend/package.json
- ui.tests/test-module/specs/image/image.authoring.cy.js
- ui.tests/test-module/specs/image/image.runtime.cy.js
> Master65027 jan

- ui.frontend/src/GuideBridge.js
> Fixing cross origin issues (#1518)

- .circleci/config.yml
- bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/aemform/AEMFormImpl.java
- bundles/core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/aemform/AEMFormImplTest.java
- bundles/core/src/test/resources/aemform/test-content.json
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/hamburgerMenu.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/container.html
- ui.frontend/package-lock.json
- ui.frontend/package.json
- ui.tests/test-module/specs/formContainer/formContainer.runtime.cy.js
> Dev master24 feb

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v1/container/clientlibs/editor/js/editDialog.js
- ui.tests/test-module/specs/formcontainer.cy.js
> FORMS-16007 : rest endpoint url validation, to not allow relative url 

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/js/textinputview.js
> Fixing positional enter in text area.

- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/actions/submit/v1/submit/README.md
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/button/v1/button/clientlibs/site/js/buttonview.js
- ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/README.md
- ui.tests/test-module/specs/actions/submit/submit.runtime.cy.js
This PR addresses [Issue #1215](https://github.com/adobe/aem-core-forms-components/issues/1215), which reported that clicking the **Submit** button multiple times triggered multiple form submissions, resulting in duplicate entries.
To resolve this, a loader has been introduced that appears on form submission. While the loader is active, the form is disabled, preventing duplicate submits until the process is complete.
- Fixes [Issue #1215](https://github.com/adobe/aem-core-forms-components/issues/1215)
Multiple submissions from repeated clicks on the **Submit** button were leading to duplicate form entries, which negatively impacted both user experience and backend data integrity.  
By introducing a loader that disables the form during submission, this fix ensures that only one submission …
> Feat: added the loader to avoid multiple submits and tests
